import React,{useEffect,useMemo,useRef,useState}from'react';
import L from'leaflet';
import'leaflet/dist/leaflet.css';
import'./field-flow.css';

const DEFAULT_CENTER=[23.2494,-106.4111];
const rad=x=>x*Math.PI/180;
const hav=(a,b)=>{const R=6371000,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),la1=rad(a.lat),la2=rad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const fmt=(n,d=0)=>Number.isFinite(Number(n))?Number(n).toLocaleString('es-MX',{maximumFractionDigits:d}):'—';
const metric=poly=>{if(!poly||poly.length<3)return{area:0,perimeter:0};const lat0=rad(poly.reduce((s,p)=>s+p[0],0)/poly.length),xy=poly.map(([lat,lng])=>({x:lng*111320*Math.cos(lat0),y:lat*110540}));let s=0,p=0;for(let i=0;i<poly.length;i++){const a=xy[i],b=xy[(i+1)%xy.length];s+=a.x*b.y-b.x*a.y;p+=hav({lat:poly[i][0],lng:poly[i][1]},{lat:poly[(i+1)%poly.length][0],lng:poly[(i+1)%poly.length][1]})}return{area:Math.abs(s)/2,perimeter:p}};
const pointInPoly=(p,poly)=>{if(!p||!poly?.length)return false;let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const yi=poly[i][0],xi=poly[i][1],yj=poly[j][0],xj=poly[j][1];const hit=((yi>p.lat)!==(yj>p.lat))&&(p.lng<(xj-xi)*(p.lat-yi)/(yj-yi+1e-12)+xi);if(hit)inside=!inside}return inside};

async function reverseLookup(g){const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${g.lat}&lon=${g.lng}&zoom=18&addressdetails=1`,{headers:{'Accept-Language':'es'}});if(!r.ok)throw new Error();return r.json()}
async function detectArea(g){const q=`[out:json][timeout:10];(way(around:90,${g.lat},${g.lng})[landuse];way(around:90,${g.lat},${g.lng})[building];);out tags geom;`;const r=await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`);if(!r.ok)return null;const j=await r.json();const polys=(j.elements||[]).filter(e=>e.geometry?.length>=4).map(e=>({poly:e.geometry.map(p=>[p.lat,p.lon]),tags:e.tags||{}})).filter(x=>pointInPoly(g,x.poly)).map(x=>({...x,m:metric(x.poly)})).filter(x=>x.m.area>20&&x.m.area<150000).sort((a,b)=>a.m.area-b.m.area);return polys[0]||null}

function useCompass(){const[heading,setHeading]=useState(null);const enable=async()=>{try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')await DeviceOrientationEvent.requestPermission()}catch{};window.addEventListener('deviceorientation',e=>{const h=Number.isFinite(e.webkitCompassHeading)?e.webkitCompassHeading:Number.isFinite(e.alpha)?(360-e.alpha)%360:null;if(h!=null)setHeading(h)},{once:false})};return{heading,enable}}

function FieldMap({gps,poly,track,findings,draw,onDraw,base}){const host=useRef(null),map=useRef(null),layer=useRef(null),tile=useRef(null),fitted=useRef(false);useEffect(()=>{const m=L.map(host.current,{zoomControl:false,attributionControl:false}).setView(DEFAULT_CENTER,13);L.control.zoom({position:'bottomright'}).addTo(m);layer.current=L.layerGroup().addTo(m);map.current=m;return()=>m.remove()},[]);useEffect(()=>{if(!map.current)return;if(tile.current)map.current.removeLayer(tile.current);tile.current=base==='sat'?L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20}):L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20});tile.current.addTo(map.current)},[base]);useEffect(()=>{if(!map.current)return;const h=e=>draw&&onDraw?.([e.latlng.lat,e.latlng.lng]);map.current.on('click',h);return()=>map.current.off('click',h)},[draw,onDraw]);useEffect(()=>{const m=map.current,l=layer.current;if(!m||!l)return;l.clearLayers();if(poly?.length>=2){L.polyline([...poly,poly.length>=3?poly[0]:null].filter(Boolean),{color:'#ffffff',weight:4}).addTo(l);if(poly.length>=3)L.polygon(poly,{color:'#ffffff',weight:2,fillColor:'#ffffff',fillOpacity:.08}).addTo(l);poly.forEach((p,i)=>L.circleMarker(p,{radius:5,color:'#0b1210',weight:2,fillColor:'#fff',fillOpacity:1}).bindTooltip(`${i+1}`).addTo(l))}if(track?.length>1)L.polyline(track.map(p=>[p.lat,p.lng]),{color:'#d8b36a',weight:4}).addTo(l);findings.forEach(f=>L.circleMarker([f.lat,f.lng],{radius:7,color:'#fff',weight:2,fillColor:f.kind==='Riesgo'?'#b95d4f':'#d8b36a',fillOpacity:1}).bindTooltip(f.kind).addTo(l));if(gps){L.circle([gps.lat,gps.lng],{radius:gps.accuracy||0,color:'#9eb5aa',weight:1,fillOpacity:.06}).addTo(l);L.circleMarker([gps.lat,gps.lng],{radius:8,color:'#fff',weight:3,fillColor:'#12201a',fillOpacity:1}).addTo(l);if(!fitted.current){m.setView([gps.lat,gps.lng],19);fitted.current=true}else m.panTo([gps.lat,gps.lng],{animate:true,duration:.25})}},[gps,poly,track,findings]);return <div ref={host} className="ff-map"/>}

const steps=[['site','Sitio'],['boundary','Terreno'],['inspect','Recorrido'],['report','Reporte']];

export default function FieldFlowApp(){
 const[step,setStep]=useState('site'),[gps,setGps]=useState(null),[address,setAddress]=useState(''),[locating,setLocating]=useState(false),[error,setError]=useState(''),[base,setBase]=useState('sat'),[detected,setDetected]=useState(null),[poly,setPoly]=useState([]),[delimMode,setDelimMode]=useState(null),[track,setTrack]=useState([]),[walking,setWalking]=useState(false),[findings,setFindings]=useState([]),[showFinding,setShowFinding]=useState(false),[kind,setKind]=useState('Acceso'),[note,setNote]=useState(''),[photos,setPhotos]=useState([]),[startedAt,setStartedAt]=useState(null);
 const watch=useRef(null),last=useRef(null),compass=useCompass();
 const metrics=useMemo(()=>metric(poly),[poly]);
 const walked=useMemo(()=>track.slice(1).reduce((s,p,i)=>s+hav(track[i],p),0),[track]);
 const coverage=Math.min(100,Math.round((walked/Math.max(metrics.perimeter*1.6,1))*100));
 const locate=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS no disponible'));navigator.geolocation.getCurrentPosition(p=>resolve(p),reject,{enableHighAccuracy:true,timeout:18000,maximumAge:0})});
 const apply=p=>{const g={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,alt:p.coords.altitude,speed:p.coords.speed};setGps(g);return g};
 const detect=async()=>{setLocating(true);setError('');try{const p=await locate();const g=apply(p);compass.enable();try{const a=await reverseLookup(g);setAddress(a.display_name||'Ubicación detectada')}catch{setAddress('Ubicación detectada')}try{const d=await detectArea(g);setDetected(d);if(d?.poly)setPoly(d.poly)}catch{}setStep('boundary')}catch(e){setError(e.message||'No se pudo obtener tu ubicación')}finally{setLocating(false)}};
 const addCorner=async()=>{try{const p=await locate();const g=apply(p);setPoly(x=>[...x,[g.lat,g.lng]])}catch(e){setError(e.message)}};
 const startBoundaryWalk=()=>{setDelimMode('walk');setPoly([]);setTrack([]);last.current=null;if(watch.current)navigator.geolocation.clearWatch(watch.current);watch.current=navigator.geolocation.watchPosition(p=>{const g=apply(p);if(!last.current||hav(last.current,g)>2.5){setPoly(x=>[...x,[g.lat,g.lng]]);last.current=g}},e=>setError(e.message),{enableHighAccuracy:true,maximumAge:200,timeout:20000})};
 const stopBoundaryWalk=()=>{if(watch.current){navigator.geolocation.clearWatch(watch.current);watch.current=null}setDelimMode(null)};
 const startInspect=()=>{setTrack([]);setStartedAt(new Date());setWalking(true);last.current=null;if(watch.current)navigator.geolocation.clearWatch(watch.current);watch.current=navigator.geolocation.watchPosition(p=>{const g=apply(p);if(!last.current||hav(last.current,g)>2){setTrack(x=>[...x,g]);last.current=g}},e=>setError(e.message),{enableHighAccuracy:true,maximumAge:200,timeout:20000})};
 const stopInspect=()=>{if(watch.current){navigator.geolocation.clearWatch(watch.current);watch.current=null}setWalking(false);setStep('report')};
 useEffect(()=>()=>{if(watch.current)navigator.geolocation.clearWatch(watch.current)},[]);
 const saveFinding=()=>{if(!gps)return;setFindings(x=>[...x,{id:Date.now(),kind,note,lat:gps.lat,lng:gps.lng,heading:compass.heading,at:new Date().toISOString()}]);setNote('');setShowFinding(false)};
 const addPhoto=e=>{const f=e.target.files?.[0];if(!f||!gps)return;setPhotos(x=>[...x,{id:Date.now(),name:f.name,lat:gps.lat,lng:gps.lng,at:new Date().toISOString()}]);e.target.value=''};
 const exportReport=()=>{const data={createdAt:new Date().toISOString(),address,gps,polygon:poly,metrics,walked,coverage,findings,photos};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SLTM-levantamiento.json';a.click();URL.revokeObjectURL(a.href)};
 const title=step==='site'?'Ubica el sitio':step==='boundary'?'Define el terreno':step==='inspect'?'Recorre y documenta':'Resultado del levantamiento';
 const subtitle=step==='site'?'SLTM usa tu posición para empezar.':step==='boundary'?'Confirma el límite o delimítalo en campo.':step==='inspect'?'Camina el sitio. Registra solo lo que importa.':'Una lectura clara de lo que levantaste.';
 return <div className="ff-app">
  <header><div className="ff-brand">SLTM</div><div className="ff-title"><strong>{title}</strong><span>{subtitle}</span></div><button className="ff-layer" onClick={()=>setBase(x=>x==='sat'?'street':'sat')}>{base==='sat'?'Satélite':'Calles'}</button></header>
  <main><FieldMap gps={gps} poly={poly} track={track} findings={findings} draw={step==='boundary'&&delimMode==='draw'} onDraw={p=>setPoly(x=>[...x,p])} base={base}/>
   <section className="ff-sheet">
    {error&&<div className="ff-error">{error}</div>}
    {step==='site'&&<div className="ff-stage"><div className="ff-kicker">PASO 1 DE 4</div><h1>Empieza donde estás.</h1><p>Detectamos tu posición y usamos el mapa solo como punto de partida. Después tú confirmas el terreno real.</p><button className="ff-primary" onClick={detect} disabled={locating}>{locating?'Ubicando…':'Detectar mi ubicación'}</button></div>}
    {step==='boundary'&&<div className="ff-stage"><div className="ff-kicker">PASO 2 DE 4</div><div className="ff-location"><span>Estás aquí</span><strong>{address||'Ubicación detectada'}</strong><small>GPS ± {fmt(gps?.accuracy,1)} m</small></div>{poly.length>=3&&<div className="ff-metrics"><div><b>{fmt(metrics.area)}</b><span>m²</span><small>Área</small></div><div><b>{fmt(metrics.perimeter)}</b><span>m</span><small>Perímetro</small></div><div><b>{poly.length}</b><span>pts</span><small>Vértices</small></div></div>}<div className="ff-choice"><strong>{detected?'Encontramos un límite cartográfico. ¿Te sirve?':'¿Cómo quieres definir el terreno?'}</strong><span>Si no coincide con el predio real, corrígelo aquí.</span></div><div className="ff-actions">{detected&&poly.length>=3&&<button onClick={()=>setStep('inspect')}>Usar este límite</button>}<button onClick={()=>{setPoly([]);setDelimMode('corner')}}>Marcar esquinas</button><button onClick={()=>{setPoly([]);setDelimMode('draw')}}>Dibujar en mapa</button><button onClick={delimMode==='walk'?stopBoundaryWalk:startBoundaryWalk}>{delimMode==='walk'?'Terminar recorrido':'Caminar perímetro'}</button></div>{delimMode==='corner'&&<button className="ff-primary" onClick={addCorner}>+ Registrar esta esquina</button>}{poly.length>=3&&!detected&&<button className="ff-primary" onClick={()=>setStep('inspect')}>Continuar con este terreno</button>}</div>}
    {step==='inspect'&&<div className="ff-stage"><div className="ff-kicker">PASO 3 DE 4</div><div className="ff-metrics"><div><b>{fmt(walked)}</b><span>m</span><small>Recorridos</small></div><div><b>{coverage}</b><span>%</span><small>Cobertura</small></div><div><b>{findings.length}</b><span></span><small>Hallazgos</small></div></div><div className="ff-progress"><i style={{width:`${coverage}%`}}/></div><p className="ff-guidance">{walking?'Camina el sitio. Cuando veas algo relevante, regístralo.':'Inicia el recorrido para que SLTM documente por dónde pasaste.'}</p><div className="ff-inspect-actions">{!walking?<button className="ff-primary" onClick={startInspect}>Iniciar recorrido</button>:<><button className="ff-record" onClick={()=>setShowFinding(true)}>+ Registrar hallazgo</button><label className="ff-camera">Cámara<input type="file" accept="image/*" capture="environment" onChange={addPhoto}/></label><button className="ff-stop" onClick={stopInspect}>Finalizar</button></>}</div></div>}
    {step==='report'&&<div className="ff-stage ff-report"><div className="ff-kicker">PASO 4 DE 4</div><div className="ff-score"><span>Levantamiento completado</span><strong>{coverage}%</strong><small>cobertura estimada del recorrido</small></div><div className="ff-metrics four"><div><b>{fmt(metrics.area)}</b><span>m²</span><small>Área</small></div><div><b>{fmt(metrics.perimeter)}</b><span>m</span><small>Perímetro</small></div><div><b>{fmt(walked)}</b><span>m</span><small>Recorrido</small></div><div><b>{findings.length+photos.length}</b><span></span><small>Evidencias</small></div></div><div className="ff-summary"><strong>Resumen de campo</strong>{findings.length?findings.map(f=><div key={f.id}><span>{f.kind}</span><p>{f.note||'Sin nota adicional'} · {f.lat.toFixed(5)}, {f.lng.toFixed(5)}</p></div>):<p>No registraste incidencias. El recorrido quedó guardado como evidencia espacial.</p>}</div><button className="ff-primary" onClick={exportReport}>Exportar levantamiento</button><button className="ff-ghost" onClick={()=>setStep('inspect')}>Volver al mapa</button></div>}
   </section>
  </main>
  <nav className="ff-nav">{steps.map(([id,label],i)=><button key={id} className={step===id?'active':''} onClick={()=>{if(id==='site'||gps)setStep(id)}}><span>{i+1}</span>{label}</button>)}</nav>
  {showFinding&&<div className="ff-modal"><div><button className="ff-x" onClick={()=>setShowFinding(false)}>×</button><span className="ff-kicker">NUEVO HALLAZGO</span><h2>¿Qué encontraste aquí?</h2><div className="ff-types">{['Acceso','Drenaje','Servicios','Obstáculo','Vegetación','Riesgo'].map(x=><button key={x} className={kind===x?'active':''} onClick={()=>setKind(x)}>{x}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota breve (opcional)"/><div className="ff-meta">GPS ± {fmt(gps?.accuracy,1)} m {compass.heading!=null?`· rumbo ${Math.round(compass.heading)}°`:''}</div><button className="ff-primary" onClick={saveFinding}>Guardar en este punto</button></div></div>}
 </div>
}
