import React,{useEffect,useMemo,useRef,useState}from'react';
import L from'leaflet';
import'leaflet/dist/leaflet.css';
import ModernFieldApp from'./ModernFieldApp';
import'./hybrid-field.css';
import{saveMedia}from'./mediaDb';
import{queueTerrain,queueVisitBundle}from'./api';

const TERRAIN_KEY='sltm_modern_terrains_v1';
const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const finite=v=>Number.isFinite(Number(v));
const hav=(a,b)=>{const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const routeDistance=pts=>pts.slice(1).reduce((s,p,i)=>s+hav(pts[i],p),0);
const median=xs=>{const a=xs.filter(finite).map(Number).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const labels={relleno:'Relleno / corte',drenaje:'Drenaje',vegetacion:'Vegetación',desmonte:'Desmonte',erosion:'Erosión / talud',construccion:'Construcción',residuo:'Residuo / descarga',acceso:'Acceso',suelo:'Suelo',otro:'Otro'};

function readTerrains(){try{return JSON.parse(localStorage.getItem(TERRAIN_KEY)||'[]')}catch{return[]}}

function usePhoneSensors(active){
 const[gps,setGps]=useState(null),[gpsError,setGpsError]=useState(''),[heading,setHeading]=useState(null),[tilt,setTilt]=useState({beta:null,gamma:null}),[motion,setMotion]=useState(null),[enabled,setEnabled]=useState(false);
 useEffect(()=>{if(!active||!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>{setGpsError('');setGps({lat:p.coords.latitude,lng:p.coords.longitude,alt:p.coords.altitude,altAcc:p.coords.altitudeAccuracy,acc:p.coords.accuracy,speed:p.coords.speed,course:p.coords.heading,at:now()})},e=>setGpsError(e.message),{enableHighAccuracy:true,maximumAge:300,timeout:20000});return()=>navigator.geolocation.clearWatch(id)},[active]);
 useEffect(()=>{if(!active||!enabled)return;const o=e=>{const hd=finite(e.webkitCompassHeading)?Number(e.webkitCompassHeading):finite(e.alpha)?(360-Number(e.alpha))%360:null;if(finite(hd))setHeading(hd);setTilt({beta:finite(e.beta)?Number(e.beta):null,gamma:finite(e.gamma)?Number(e.gamma):null})};const m=e=>{const a=e.accelerationIncludingGravity||e.acceleration;if(a&&finite(a.x)&&finite(a.y)&&finite(a.z))setMotion(Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z))};window.addEventListener('deviceorientation',o,true);window.addEventListener('devicemotion',m,true);return()=>{window.removeEventListener('deviceorientation',o,true);window.removeEventListener('devicemotion',m,true)}},[active,enabled]);
 const enable=async()=>{let ok=true;try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')ok=(await DeviceOrientationEvent.requestPermission())==='granted'}catch{ok=false}try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')await DeviceMotionEvent.requestPermission()}catch{}setEnabled(ok);return ok};
 return{gps,gpsError,heading,tilt,motion,enable};
}

function useCamera(active){
 const videoRef=useRef(null),streamRef=useRef(null);const[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!active)return;let cancelled=false;(async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('La cámara no está disponible en este navegador');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});if(cancelled){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();setReady(true)}}catch(e){setError(e.message||'No fue posible abrir la cámara')}})();return()=>{cancelled=true;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setReady(false)}},[active]);
 const shot=async()=>{const v=videoRef.current;if(!v||!ready)return null;const c=document.createElement('canvas');const max=1600,scale=Math.min(1,max/Math.max(v.videoWidth||1280,v.videoHeight||720));c.width=Math.max(1,Math.round((v.videoWidth||1280)*scale));c.height=Math.max(1,Math.round((v.videoHeight||720)*scale));c.getContext('2d',{alpha:false}).drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.86));return blob?new File([blob],`sltm-${Date.now()}.jpg`,{type:'image/jpeg'}):null};
 return{videoRef,ready,error,shot};
}

function MiniMap({terrain,gps,track,points}){
 const host=useRef(null),map=useRef(null),layer=useRef(null);
 useEffect(()=>{const m=L.map(host.current,{zoomControl:false,attributionControl:false}).setView([23.2494,-106.4111],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20}).addTo(m);layer.current=L.layerGroup().addTo(m);map.current=m;setTimeout(()=>m.invalidateSize(),80);return()=>m.remove()},[]);
 useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();if(terrain?.poly?.length>=3)L.polygon(terrain.poly,{color:'#111713',weight:2,fillColor:'#aebbb2',fillOpacity:.18}).addTo(g);if(track.length>1)L.polyline(track.map(p=>[p.lat,p.lng]),{color:'#101511',weight:3}).addTo(g);points.forEach(p=>L.circleMarker([p.lat,p.lng],{radius:5,color:'#fff',weight:2,fillColor:p.severity==='alta'?'#a13f34':p.severity==='media'?'#8f6f27':'#42604d',fillOpacity:1}).addTo(g));if(gps){L.circle([gps.lat,gps.lng],{radius:gps.acc||0,color:'#68766d',weight:1,fillOpacity:.03}).addTo(g);L.circleMarker([gps.lat,gps.lng],{radius:6,color:'#fff',weight:2,fillColor:'#111',fillOpacity:1}).addTo(g);m.setView([gps.lat,gps.lng],Math.max(m.getZoom(),17))}},[terrain,gps,track,points]);
 return <div ref={host} className="hf-minimap"/>
}

function Spark({values,min,max}){const clean=values.map(v=>finite(v)?Number(v):null),xs=clean.filter(finite),lo=finite(min)?Number(min):(xs.length?Math.min(...xs):0),hi=finite(max)?Number(max):(xs.length?Math.max(...xs):1),span=Math.max(1e-6,hi-lo),pts=clean.map((v,i)=>v==null?null:`${(i/Math.max(1,clean.length-1))*100},${28-((v-lo)/span)*28}`).filter(Boolean).join(' ');return <svg viewBox="0 0 100 28" preserveAspectRatio="none" className="hf-spark"><line x1="0" y1="27.5" x2="100" y2="27.5"/><polyline points={pts}/></svg>}
function SensorCard({label,value,unit,values}){return <div className="hf-sensor-card"><div className="hf-sensor-label">{label}</div><div className="hf-sensor-value">{value}<small>{unit}</small></div><Spark values={values}/></div>}

function InstrumentedCapture({onClose}){
 const terrains=useMemo(readTerrains,[]),[step,setStep]=useState('setup'),[terrainId,setTerrainId]=useState(''),[siteName,setSiteName]=useState(''),[mission,setMission]=useState('ordenamiento ecológico'),[kind,setKind]=useState('relleno'),[severity,setSeverity]=useState('media'),[note,setNote]=useState(''),[track,setTrack]=useState([]),[points,setPoints]=useState([]),[evidence,setEvidence]=useState([]),[telemetry,setTelemetry]=useState({acc:[],alt:[],speed:[],heading:[],tilt:[],motion:[]}),[startedAt,setStartedAt]=useState(null),[flash,setFlash]=useState(false),[saving,setSaving]=useState(false);
 const sensors=usePhoneSensors(step==='capture'),camera=useCamera(step==='capture'),lastTrack=useRef(null);const selected=terrains.find(t=>t.id===terrainId)||null;
 useEffect(()=>{if(step!=='capture'||!sensors.gps)return;const moved=!lastTrack.current?Infinity:hav(lastTrack.current,sensors.gps);if(sensors.gps.acc<=35&&(!lastTrack.current||moved>=4)){lastTrack.current=sensors.gps;setTrack(v=>[...v,sensors.gps])}},[step,sensors.gps]);
 useEffect(()=>{if(step!=='capture')return;const id=setInterval(()=>setTelemetry(t=>({acc:[...t.acc.slice(-39),sensors.gps?.acc??null],alt:[...t.alt.slice(-39),sensors.gps?.alt??null],speed:[...t.speed.slice(-39),finite(sensors.gps?.speed)?Number(sensors.gps.speed)*3.6:null],heading:[...t.heading.slice(-39),sensors.heading??sensors.gps?.course??null],tilt:[...t.tilt.slice(-39),finite(sensors.tilt.beta)?Math.abs(Number(sensors.tilt.beta)):null],motion:[...t.motion.slice(-39),sensors.motion??null]})),700);return()=>clearInterval(id)},[step,sensors.gps,sensors.heading,sensors.tilt.beta,sensors.motion]);
 const start=async()=>{await sensors.enable();setStartedAt(now());setStep('capture')};
 const addPoint=async photo=>{if(!sensors.gps)return;const p={id:uid('O'),kind,severity,note:note.trim(),lat:sensors.gps.lat,lng:sensors.gps.lng,alt:sensors.gps.alt,acc:sensors.gps.acc,speed:sensors.gps.speed,heading:sensors.heading,pitch:sensors.tilt.beta,roll:sensors.tilt.gamma,motion:sensors.motion,at:now()};setPoints(v=>[...v,p]);if(photo){const file=await camera.shot();if(file){const id=uid('E');await saveMedia(id,file);setEvidence(v=>[...v,{id,at:now(),kind,severity,note:note.trim(),gps:{...sensors.gps,heading:sensors.heading,pitch:sensors.tilt.beta,roll:sensors.tilt.gamma}}]);setFlash(true);setTimeout(()=>setFlash(false),130)}}setNote('')};
 const finish=async()=>{if(!sensors.gps)return;setSaving(true);try{let terrain=selected,tid=selected?.id;if(!terrain){tid=uid('SITE');terrain={id:tid,name:siteName.trim()||'Sitio de campo',status:'Activo',purpose:mission,createdAt:startedAt||now(),last:today(),source:'instrumented_site',poly:[],center:[sensors.gps.lat,sensors.gps.lng],area:null,perimeter:null};queueTerrain(terrain);const current=readTerrains();localStorage.setItem(TERRAIN_KEY,JSON.stringify([...current,terrain]))}const accs=track.map(p=>p.acc).filter(finite).map(Number),visit={id:uid('V'),date:today(),startedAt:startedAt||now(),endedAt:now(),mode:'instrumented_capture',purpose:mission,track,points,evidence,distance:routeDistance(track),avgAcc:accs.length?accs.reduce((a,b)=>a+b,0)/accs.length:null,medianAcc:median(accs),quality:Math.min(100,(median(accs)<=10?35:median(accs)<=20?25:15)+Math.min(points.length*8,30)+Math.min(evidence.length*12,24)+8),telemetrySummary:{samples:telemetry.acc.length,altMin:telemetry.alt.filter(finite).length?Math.min(...telemetry.alt.filter(finite)):null,altMax:telemetry.alt.filter(finite).length?Math.max(...telemetry.alt.filter(finite)):null,maxMotion:telemetry.motion.filter(finite).length?Math.max(...telemetry.motion.filter(finite)):null}};queueVisitBundle(tid,visit);setStep('done')}finally{setSaving(false)}};
 const elapsed=startedAt?Math.max(0,Math.round((Date.now()-new Date(startedAt).getTime())/1000)):0;
 if(step==='setup')return <div className="hf-layer"><div className="hf-setup"><button className="hf-back" onClick={onClose}>← Volver</button><div className="hf-setup-kicker">CAMPO INSTRUMENTADO</div><h1>Captura visual + sensores del teléfono.</h1><p>La cámara es la vista principal. Las gráficas muestran únicamente datos que el navegador recibe del dispositivo en tiempo real.</p><div className="hf-form-grid"><label>Terreno<select value={terrainId} onChange={e=>setTerrainId(e.target.value)}><option value="">Nueva ubicación</option>{terrains.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{!terrainId&&<label>Nombre del sitio<input value={siteName} onChange={e=>setSiteName(e.target.value)} placeholder="Ej. Borde de estero"/></label>}<label>Tipo de misión<select value={mission} onChange={e=>setMission(e.target.value)}><option>ordenamiento ecológico</option><option>inspección de cambio</option><option>factibilidad física</option><option>inventario de terreno</option></select></label></div><div className="hf-capabilities"><span>Cámara trasera</span><span>GPS / GNSS</span><span>Brújula</span><span>Inclinación</span><span>Movimiento</span></div><button className="hf-primary" disabled={!terrainId&&!siteName.trim()} onClick={start}>Abrir cámara de campo</button></div></div>;
 if(step==='done')return <div className="hf-layer"><div className="hf-done"><div className="hf-done-icon">✓</div><span>SESIÓN CERRADA</span><h2>Captura guardada.</h2><div className="hf-done-grid"><b>{points.length}<small>puntos</small></b><b>{evidence.length}<small>fotos</small></b><b>{Math.round(routeDistance(track))}<small>m recorridos</small></b><b>{finite(median(track.map(p=>p.acc)))?`±${Math.round(median(track.map(p=>p.acc)))} m`:'—'}<small>precisión mediana</small></b></div><button className="hf-primary" onClick={onClose}>Volver al inventario</button></div></div>;
 const acc=sensors.gps?.acc,accLabel=!finite(acc)?'Sin GPS':acc<=8?'Excelente':acc<=15?'Buena':acc<=25?'Utilizable':'Baja';
 return <div className="hf-layer hf-capture"><video ref={camera.videoRef} className="hf-video" autoPlay muted playsInline/><div className="hf-camera-shade"/><div className={`hf-flash ${flash?'show':''}`}/><div className="hf-reticle"><i/><i/></div><div className="hf-top"><button onClick={onClose}>← Salir</button><div><span>SLTM · CAMPO</span><b>{selected?.name||siteName}</b></div><div className="hf-live"><i/> EN VIVO · {Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</div></div><div className="hf-left-hud"><div className="hf-gps-pill"><span>{accLabel}</span><b>{finite(acc)?`±${Math.round(acc)} m`:'GPS…'}</b></div><MiniMap terrain={selected} gps={sensors.gps} track={track} points={points}/></div><div className="hf-right-hud"><div className="hf-panel-title">TELEMETRÍA DEL DISPOSITIVO</div><div className="hf-sensor-grid"><SensorCard label="Precisión GPS" value={finite(acc)?Math.round(acc):'—'} unit="m" values={telemetry.acc}/><SensorCard label="Altitud" value={finite(sensors.gps?.alt)?Math.round(sensors.gps.alt):'—'} unit="m" values={telemetry.alt}/><SensorCard label="Velocidad" value={finite(sensors.gps?.speed)?(sensors.gps.speed*3.6).toFixed(1):'—'} unit="km/h" values={telemetry.speed}/><SensorCard label="Rumbo" value={finite(sensors.heading)?Math.round(sensors.heading):finite(sensors.gps?.course)?Math.round(sensors.gps.course):'—'} unit="°" values={telemetry.heading}/><SensorCard label="Inclinación" value={finite(sensors.tilt.beta)?Math.round(Math.abs(sensors.tilt.beta)):'—'} unit="°" values={telemetry.tilt}/><SensorCard label="Movimiento" value={finite(sensors.motion)?sensors.motion.toFixed(1):'—'} unit="m/s²" values={telemetry.motion}/></div><div className="hf-session-stats"><span><b>{Math.round(routeDistance(track))}</b> m recorrido</span><span><b>{points.length}</b> puntos</span><span><b>{evidence.length}</b> fotos</span></div></div><div className="hf-bottom"><div className="hf-bottom-form"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option></select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe lo que observas"/></div><div className="hf-bottom-actions"><button onClick={()=>addPoint(false)} disabled={!sensors.gps}>Registrar punto</button><button className="hf-shutter" onClick={()=>addPoint(true)} disabled={!sensors.gps||!camera.ready}><i/></button><button className="hf-finish" onClick={finish} disabled={!sensors.gps||saving}>{saving?'Guardando…':'Cerrar sesión'}</button></div><small>{camera.error||sensors.gpsError||(!camera.ready?'Preparando cámara…':'El botón central guarda foto + coordenada + sensores en el mismo instante.')}</small></div></div>
}

export default function HybridFieldApp(){const[mode,setMode]=useState('app');return <div className="hf-root">{mode==='app'?<><ModernFieldApp/><button className="hf-launch" onClick={()=>setMode('capture')}><span>◉</span><div><b>Campo instrumentado</b><small>Cámara + sensores en vivo</small></div></button></>:<InstrumentedCapture onClose={()=>setMode('app')}/>}</div>}
