import React,{useEffect,useMemo,useRef,useState}from'react';
import L from'leaflet';
import'leaflet/dist/leaflet.css';
import'./instrumented-ops.css';
import{saveMedia}from'./mediaDb';
import{queueTerrain,queueVisitBundle,pullWorkspace,flushQueue,pingApi,getSyncSnapshot,exportGeoJsonUrl}from'./api';

const TKEY='sltm_instrumented_terrains_v1';
const VKEY='sltm_instrumented_visits_v1';
const SKEY='sltm_instrumented_session_v1';
const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const finite=v=>Number.isFinite(Number(v));
const fmt=(n,d=0)=>finite(n)?Number(n).toLocaleString('es-MX',{maximumFractionDigits:d}):'—';
const median=xs=>{const a=xs.filter(finite).map(Number).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const hav=(a,b)=>{const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const routeDistance=pts=>pts.slice(1).reduce((s,p,i)=>s+hav(pts[i],p),0);
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const kinds={relleno:'Relleno / corte',drenaje:'Drenaje',vegetacion:'Vegetación',desmonte:'Desmonte',erosion:'Erosión / talud',construccion:'Construcción',residuo:'Residuo / descarga',acceso:'Acceso',suelo:'Suelo',otro:'Otro'};

function useSync(){
 const[s,setS]=useState(()=>getSyncSnapshot());
 useEffect(()=>{const h=e=>setS(v=>({...v,...e.detail}));window.addEventListener('sltm-sync',h);pingApi();flushQueue();return()=>window.removeEventListener('sltm-sync',h)},[]);
 return s;
}

function useSensors(active){
 const[gps,setGps]=useState(null),[gpsError,setGpsError]=useState(''),[heading,setHeading]=useState(null),[tilt,setTilt]=useState({beta:null,gamma:null}),[motion,setMotion]=useState({acc:null,rot:null});
 const[permissions,setPermissions]=useState({orientation:false,motion:false});
 useEffect(()=>{if(!active||!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>{setGpsError('');setGps({lat:p.coords.latitude,lng:p.coords.longitude,alt:p.coords.altitude,altAcc:p.coords.altitudeAccuracy,acc:p.coords.accuracy,speed:p.coords.speed,course:p.coords.heading,at:now()})},e=>setGpsError(e.message),{enableHighAccuracy:true,maximumAge:300,timeout:20000});return()=>navigator.geolocation.clearWatch(id)},[active]);
 useEffect(()=>{if(!active||!permissions.orientation)return;const h=e=>{const hd=finite(e.webkitCompassHeading)?Number(e.webkitCompassHeading):finite(e.alpha)?(360-Number(e.alpha))%360:null;setHeading(hd);setTilt({beta:finite(e.beta)?Number(e.beta):null,gamma:finite(e.gamma)?Number(e.gamma):null})};window.addEventListener('deviceorientation',h,true);return()=>window.removeEventListener('deviceorientation',h,true)},[active,permissions.orientation]);
 useEffect(()=>{if(!active||!permissions.motion)return;const h=e=>{const a=e.accelerationIncludingGravity||e.acceleration;let mag=null;if(a&&finite(a.x)&&finite(a.y)&&finite(a.z))mag=Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z);const r=e.rotationRate;let rot=null;if(r&&finite(r.alpha)&&finite(r.beta)&&finite(r.gamma))rot=Math.sqrt(r.alpha*r.alpha+r.beta*r.beta+r.gamma*r.gamma);setMotion({acc:mag,rot})};window.addEventListener('devicemotion',h,true);return()=>window.removeEventListener('devicemotion',h,true)},[active,permissions.motion]);
 const request=async()=>{let o=true,m=true;try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')o=(await DeviceOrientationEvent.requestPermission())==='granted'}catch{o=false}try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')m=(await DeviceMotionEvent.requestPermission())==='granted'}catch{m=false}setPermissions({orientation:o,motion:m});return{o,m}};
 return{gps,gpsError,heading,tilt,motion,request,permissions};
}

function useCamera(active){
 const videoRef=useRef(null),streamRef=useRef(null);const[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!active)return;let dead=false;(async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});if(dead){s.getTracks().forEach(t=>t.stop());return}streamRef.current=s;if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play();setReady(true)}}catch(e){setError(e.message||'No fue posible abrir la cámara')}})();return()=>{dead=true;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setReady(false)}},[active]);
 const snap=async()=>{const v=videoRef.current;if(!v||!ready)return null;const c=document.createElement('canvas');const max=1800,scale=Math.min(1,max/Math.max(v.videoWidth||1280,v.videoHeight||720));c.width=Math.max(1,Math.round((v.videoWidth||1280)*scale));c.height=Math.max(1,Math.round((v.videoHeight||720)*scale));c.getContext('2d',{alpha:false}).drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.86));return blob?new File([blob],`sltm-${Date.now()}.jpg`,{type:'image/jpeg'}):null};
 return{videoRef,ready,error,snap};
}

function MiniMap({track,gps,points}){
 const host=useRef(null),map=useRef(null),layer=useRef(null);
 useEffect(()=>{const m=L.map(host.current,{zoomControl:false,attributionControl:false}).setView([23.2494,-106.4111],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20}).addTo(m);layer.current=L.layerGroup().addTo(m);map.current=m;setTimeout(()=>m.invalidateSize(),50);return()=>m.remove()},[]);
 useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();if(track.length>1)L.polyline(track.map(p=>[p.lat,p.lng]),{color:'#cbff6b',weight:3}).addTo(g);points.forEach(p=>L.circleMarker([p.lat,p.lng],{radius:5,color:'#07100b',weight:2,fillColor:'#cbff6b',fillOpacity:1}).addTo(g));if(gps){L.circle([gps.lat,gps.lng],{radius:gps.acc||0,color:'#9ca99f',weight:1,fillOpacity:.03}).addTo(g);L.circleMarker([gps.lat,gps.lng],{radius:5,color:'#fff',weight:2,fillColor:'#111',fillOpacity:1}).addTo(g);m.setView([gps.lat,gps.lng],Math.max(m.getZoom(),17))}},[track,gps,points]);
 return <div ref={host} className="io-mini-map"/>;
}

function Spark({values,min,max,invert=false}){
 const clean=values.map(v=>finite(v)?Number(v):null);const xs=clean.filter(finite);const lo=finite(min)?Number(min):(xs.length?Math.min(...xs):0),hi=finite(max)?Number(max):(xs.length?Math.max(...xs):1);const span=Math.max(1e-6,hi-lo);const pts=clean.map((v,i)=>v==null?null:`${(i/Math.max(1,clean.length-1))*100},${invert?((v-lo)/span)*28:28-((v-lo)/span)*28}`).filter(Boolean).join(' ');
 return <svg viewBox="0 0 100 28" preserveAspectRatio="none" className="io-spark"><line x1="0" y1="27.5" x2="100" y2="27.5"/><polyline points={pts}/></svg>
}

function Metric({label,value,unit,values,good}){return <div className="io-metric"><div><span>{label}</span><i className={good===true?'ok':good===false?'bad':''}/></div><strong>{value}<small>{unit||''}</small></strong><Spark values={values||[]}/></div>}

function Capture({terrains,onSaved,onExit}){
 const[config,setConfig]=useState(()=>read(SKEY,{siteName:'',terrainId:'',purpose:'ordenamiento ecológico'}));const[active,setActive]=useState(false),[track,setTrack]=useState([]),[points,setPoints]=useState([]),[evidence,setEvidence]=useState([]),[kind,setKind]=useState('relleno'),[note,setNote]=useState(''),[severity,setSeverity]=useState('media'),[telemetry,setTelemetry]=useState({acc:[],alt:[],speed:[],heading:[],tilt:[],motion:[]}),[startedAt,setStartedAt]=useState(null),[flash,setFlash]=useState(false),[saving,setSaving]=useState(false);
 const sensors=useSensors(active),camera=useCamera(active),lastTrack=useRef(null);
 const selected=terrains.find(t=>t.id===config.terrainId)||null;
 useEffect(()=>write(SKEY,config),[config]);
 useEffect(()=>{if(!active||!sensors.gps)return;const g=sensors.gps,moved=!lastTrack.current?Infinity:hav(lastTrack.current,g);if(g.acc<=35&&(!lastTrack.current||moved>=4)){lastTrack.current=g;setTrack(v=>[...v,g])}},[active,sensors.gps]);
 useEffect(()=>{if(!active)return;const id=setInterval(()=>setTelemetry(t=>({acc:[...t.acc.slice(-49),sensors.gps?.acc??null],alt:[...t.alt.slice(-49),sensors.gps?.alt??null],speed:[...t.speed.slice(-49),finite(sensors.gps?.speed)?Number(sensors.gps.speed)*3.6:null],heading:[...t.heading.slice(-49),sensors.heading??sensors.gps?.course??null],tilt:[...t.tilt.slice(-49),finite(sensors.tilt.beta)?Math.abs(Number(sensors.tilt.beta)):null],motion:[...t.motion.slice(-49),sensors.motion.acc??null]})),700);return()=>clearInterval(id)},[active,sensors.gps,sensors.heading,sensors.tilt.beta,sensors.motion.acc]);
 const start=async()=>{await sensors.request();setStartedAt(now());setActive(true)};
 const captureEvidence=async()=>{if(!sensors.gps)return null;const file=await camera.snap();if(!file)return null;const id=uid('E');await saveMedia(id,file);const ev={id,at:now(),gps:{...sensors.gps,heading:sensors.heading,pitch:sensors.tilt.beta,roll:sensors.tilt.gamma},kind,severity,note:note.trim()};setEvidence(v=>[...v,ev]);setFlash(true);setTimeout(()=>setFlash(false),140);return ev};
 const addPoint=async withPhoto=>{if(!sensors.gps)return;const p={id:uid('O'),kind,severity,note:note.trim(),lat:sensors.gps.lat,lng:sensors.gps.lng,alt:sensors.gps.alt,acc:sensors.gps.acc,speed:sensors.gps.speed,heading:sensors.heading,pitch:sensors.tilt.beta,roll:sensors.tilt.gamma,motion:sensors.motion.acc,at:now()};setPoints(v=>[...v,p]);if(withPhoto)await captureEvidence();setNote('')};
 const finish=async()=>{if(!sensors.gps||(!config.siteName.trim()&&!selected))return;setSaving(true);try{let terrain=selected,terrainId=selected?.id;if(!terrain){terrainId=uid('SITE');terrain={id:terrainId,name:config.siteName.trim(),status:'Activo',purpose:config.purpose,createdAt:startedAt||now(),last:today(),source:'instrumented_site',poly:[],center:[sensors.gps.lat,sensors.gps.lng],area:null,perimeter:null};queueTerrain(terrain)}const accs=track.map(p=>p.acc).filter(finite).map(Number),visit={id:uid('V'),date:today(),startedAt:startedAt||now(),endedAt:now(),mode:'instrumented_capture',purpose:config.purpose,track,points,evidence,distance:routeDistance(track),avgAcc:accs.length?accs.reduce((a,b)=>a+b,0)/accs.length:null,medianAcc:median(accs),quality:Math.min(100,(median(accs)<=10?35:median(accs)<=20?25:15)+Math.min(points.length*8,30)+Math.min(evidence.length*12,24)+(sensors.permissions.orientation?6:0)+(sensors.permissions.motion?5:0)),telemetrySummary:{samples:telemetry.acc.length,altMin:telemetry.alt.filter(finite).length?Math.min(...telemetry.alt.filter(finite)):null,altMax:telemetry.alt.filter(finite).length?Math.max(...telemetry.alt.filter(finite)):null,maxMotion:telemetry.motion.filter(finite).length?Math.max(...telemetry.motion.filter(finite)):null}};queueVisitBundle(terrainId,visit);onSaved(terrain,visit);localStorage.removeItem(SKEY);setActive(false)}finally{setSaving(false)}};
 const acc=sensors.gps?.acc,quality=!finite(acc)?'SIN GPS':acc<=8?'EXCELENTE':acc<=15?'BUENA':acc<=25?'UTILIZABLE':'BAJA';
 if(!active)return <div className="io-setup"><div className="io-setup-card"><div className="io-kicker">CAMPO INSTRUMENTADO</div><h1>Convierte el celular en una consola de inspección.</h1><p>La cámara es la vista principal. GPS, orientación, inclinación y movimiento se leen en vivo y quedan asociados a cada punto que registres.</p><div className="io-form"><label>Terreno existente<select value={config.terrainId} onChange={e=>setConfig(v=>({...v,terrainId:e.target.value}))}><option value="">Nueva ubicación / sin polígono previo</option>{terrains.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{!config.terrainId&&<label>Nombre del sitio<input value={config.siteName} onChange={e=>setConfig(v=>({...v,siteName:e.target.value}))} placeholder="Ej. Zona de relleno junto al estero"/></label>}<label>Tipo de misión<select value={config.purpose} onChange={e=>setConfig(v=>({...v,purpose:e.target.value}))}><option>ordenamiento ecológico</option><option>inspección de cambio</option><option>factibilidad física</option><option>inventario de terreno</option></select></label></div><div className="io-sensor-preview"><span>Cámara trasera</span><span>GNSS / GPS</span><span>Brújula</span><span>Inclinación</span><span>Acelerómetro</span></div><div className="io-setup-actions"><button onClick={onExit}>Volver</button><button className="primary" disabled={!config.terrainId&&!config.siteName.trim()} onClick={start}>Abrir consola de campo</button></div><small>El navegador pedirá permisos al iniciar. La disponibilidad de orientación y movimiento depende del teléfono y navegador.</small></div></div>;
 return <div className="io-capture"><video ref={camera.videoRef} className="io-video" playsInline muted autoPlay/><div className="io-video-shade"/><div className={`io-flash ${flash?'on':''}`}/><div className="io-grid-lines"/><div className="io-crosshair"><i/><i/></div>
 <div className="io-topbar"><div><b>SLTM</b><span>CAMPO INSTRUMENTADO</span></div><div className="io-live"><i/> EN VIVO</div><div className={`io-gps-state ${finite(acc)&&acc<=15?'good':finite(acc)&&acc>25?'weak':''}`}>{quality} {finite(acc)?`· ±${Math.round(acc)} m`:''}</div></div>
 <div className="io-hud-left"><div><span>LAT</span><strong>{finite(sensors.gps?.lat)?sensors.gps.lat.toFixed(6):'—'}</strong></div><div><span>LON</span><strong>{finite(sensors.gps?.lng)?sensors.gps.lng.toFixed(6):'—'}</strong></div><div><span>RUMBO</span><strong>{finite(sensors.heading)?`${Math.round(sensors.heading)}°`:'—'}</strong></div></div>
 <div className="io-mini"><MiniMap track={track} gps={sensors.gps} points={points}/></div>
 <aside className="io-telemetry"><div className="io-panel-head"><div><span>TELEMETRÍA</span><strong>{config.siteName||selected?.name||'Sitio'}</strong></div><em>{new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</em></div><div className="io-metrics"><Metric label="Precisión GNSS" value={finite(acc)?Math.round(acc):'—'} unit="m" values={telemetry.acc} good={finite(acc)?acc<=15:null}/><Metric label="Altitud" value={finite(sensors.gps?.alt)?fmt(sensors.gps.alt,1):'—'} unit="m" values={telemetry.alt}/><Metric label="Velocidad" value={finite(sensors.gps?.speed)?fmt(Number(sensors.gps.speed)*3.6,1):'—'} unit="km/h" values={telemetry.speed}/><Metric label="Rumbo" value={finite(sensors.heading)?Math.round(sensors.heading):'—'} unit="°" values={telemetry.heading} min={0} max={360}/><Metric label="Inclinación" value={finite(sensors.tilt.beta)?Math.round(Math.abs(sensors.tilt.beta)):'—'} unit="°" values={telemetry.tilt}/><Metric label="Movimiento" value={finite(sensors.motion.acc)?fmt(sensors.motion.acc,1):'—'} unit="m/s²" values={telemetry.motion}/></div><div className="io-status-grid"><div><span>Recorrido</span><b>{fmt(routeDistance(track))} m</b></div><div><span>Puntos</span><b>{points.length}</b></div><div><span>Fotos</span><b>{evidence.length}</b></div><div><span>Muestras</span><b>{telemetry.acc.length}</b></div></div></aside>
 <div className="io-capture-controls"><div className="io-type"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option></select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota rápida…"/></div><div className="io-actions"><button onClick={()=>addPoint(false)} disabled={!sensors.gps}>Registrar punto</button><button className="io-shutter" onClick={()=>addPoint(true)} disabled={!sensors.gps||!camera.ready}><i/></button><button className="finish" onClick={finish} disabled={saving||!sensors.gps}>{saving?'Guardando…':'Cerrar sesión'}</button></div><div className="io-hint">El botón central guarda <b>foto + punto + sensores</b> en el mismo instante.</div></div>
 {(camera.error||sensors.gpsError)&&<div className="io-error">{camera.error||sensors.gpsError}</div>}</div>
}

function Dashboard({terrains,visits,onCapture}){
 const recent=[...visits].sort((a,b)=>String(b.endedAt||b._serverCreatedAt||'').localeCompare(String(a.endedAt||a._serverCreatedAt||''))).slice(0,5);const geo=exportGeoJsonUrl();
 return <div className="io-dashboard"><section className="io-hero"><div className="io-kicker">SLTM · OPERACIÓN TERRITORIAL</div><h1>Inspección de campo con telemetría real.</h1><p>Una interfaz para documentar lo que existe físicamente en un sitio usando la cámara y los sensores disponibles del teléfono.</p><div className="io-hero-actions"><button className="primary" onClick={onCapture}>Nueva captura instrumentada</button>{geo&&<a href={geo} target="_blank" rel="noreferrer">Exportar GeoJSON</a>}</div></section><section className="io-overview"><div className="io-bigstat"><span>Terrenos / sitios</span><strong>{terrains.length}</strong></div><div className="io-bigstat"><span>Sesiones reales</span><strong>{visits.length}</strong></div><div className="io-bigstat"><span>Puntos registrados</span><strong>{visits.reduce((s,v)=>s+(v.points?.length||0),0)}</strong></div><div className="io-bigstat"><span>Evidencias</span><strong>{visits.reduce((s,v)=>s+(v.evidence?.length||0),0)}</strong></div></section><section className="io-dashboard-grid"><div className="io-card"><div className="io-card-head"><div><span>CAPTURA</span><h3>Qué mide el teléfono</h3></div></div><div className="io-capability-list"><div><b>GNSS</b><span>coordenada, precisión, velocidad y altitud disponible</span></div><div><b>Orientación</b><span>rumbo, inclinación y giro cuando el navegador lo expone</span></div><div><b>Movimiento</b><span>aceleración del dispositivo para contextualizar estabilidad</span></div><div><b>Cámara</b><span>evidencia visual asociada al punto y al instante de captura</span></div></div></div><div className="io-card"><div className="io-card-head"><div><span>ÚLTIMAS SESIONES</span><h3>Actividad registrada</h3></div></div>{recent.length?recent.map(v=><div className="io-session-row" key={v.id}><div><b>{terrains.find(t=>t.id===v.terrainId)?.name||v.terrainId||'Sitio'}</b><span>{v.date||'—'} · {v.mode==='instrumented_capture'?'Instrumentada':v.mode||'Visita'}</span></div><div><strong>{v.points?.length||0}</strong><span>puntos</span></div></div>):<div className="io-empty">Todavía no hay sesiones. La demo comienza cuando abras la cámara y captures datos reales.</div>}</div></section></div>
}

export default function InstrumentedOpsApp(){
 const[view,setView]=useState('dashboard'),[terrains,setTerrains]=useState(()=>read(TKEY,[])),[visits,setVisits]=useState(()=>read(VKEY,[])),[loading,setLoading]=useState(true);const sync=useSync();
 useEffect(()=>write(TKEY,terrains),[terrains]);useEffect(()=>write(VKEY,visits),[visits]);
 useEffect(()=>{(async()=>{try{const r=await pullWorkspace();if(r.terrains?.length){const m=new Map(terrains.map(t=>[t.id,t]));r.terrains.forEach(t=>m.set(t.id,{...m.get(t.id),...t}));setTerrains([...m.values()])}if(r.visits?.length){const m=new Map(visits.map(v=>[v.id,v]));r.visits.forEach(v=>m.set(v.id,{...m.get(v.id),...v}));setVisits([...m.values()])}}catch{}finally{setLoading(false)}})()},[]);
 const saved=(terrain,visit)=>{setTerrains(xs=>{const m=new Map(xs.map(t=>[t.id,t]));m.set(terrain.id,{...m.get(terrain.id),...terrain});return[...m.values()]});setVisits(xs=>[...xs.filter(v=>v.id!==visit.id),{...visit,terrainId:terrain.id}]);setView('dashboard')};
 return <div className="io-app"><header className="io-shell-head"><div className="io-brand"><b>SLTM</b><span>Spatial Land & Territory Monitor</span></div><nav><button className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')}>Operación</button><button className={view==='capture'?'active':''} onClick={()=>setView('capture')}>Campo instrumentado</button></nav><div className={`io-sync ${!sync.online?'off':sync.pending?'pending':''}`}>{!sync.online?'OFFLINE':sync.syncing?'SINCRONIZANDO':sync.pending?`${sync.pending} PENDIENTES`:sync.backend?'SINCRONIZADO':'CONECTANDO'}</div></header>{loading?<div className="io-loading">Cargando workspace…</div>:view==='capture'?<Capture terrains={terrains} onSaved={saved} onExit={()=>setView('dashboard')}/>:<Dashboard terrains={terrains} visits={visits} onCapture={()=>setView('capture')}/>}</div>
}
