import React,{useEffect,useMemo,useRef,useState}from'react';
import L from'leaflet';
import'leaflet/dist/leaflet.css';
import'./modern-field.css';
import{saveMedia}from'./mediaDb';
import{queueTerrain,queueVisitBundle,flushQueue,pingApi,pullWorkspace,getSyncSnapshot,exportGeoJsonUrl}from'./api';

const TERRAIN_STORE='sltm_modern_terrains_v1';
const VISIT_STORE='sltm_modern_visits_v1';
const DRAFT_KEY='sltm_modern_active_v1';
const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const finite=v=>Number.isFinite(Number(v));
const fmt=n=>new Intl.NumberFormat('es-MX',{maximumFractionDigits:0}).format(Number(n)||0);
const median=xs=>{const a=xs.filter(finite).map(Number).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const hav=(a,b)=>{const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const routeDistance=pts=>pts.slice(1).reduce((s,p,i)=>s+hav(pts[i],p),0);
const polygonPerimeter=pts=>pts.length<3?0:pts.reduce((s,p,i)=>s+hav(p,pts[(i+1)%pts.length]),0);
const polyArea=ll=>{if(ll.length<3)return 0;const lat0=ll.reduce((s,p)=>s+p[0],0)/ll.length*Math.PI/180,pts=ll.map(([lat,lng])=>({x:lng*111320*Math.cos(lat0),y:lat*110540}));let a=0;pts.forEach((p,i)=>{const q=pts[(i+1)%pts.length];a+=p.x*q.y-q.x*p.y});return Math.abs(a)/2};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

const purposeLabels={general:'Revisión general',relleno:'Relleno / modificación',cobertura:'Cambio de cobertura',drenaje:'Drenaje / escurrimiento',vegetacion:'Vegetación',factibilidad:'Factibilidad física'};
const findingLabels={relleno:'Relleno / corte',desmonte:'Desmonte',drenaje:'Drenaje',vegetacion:'Vegetación',erosion:'Erosión / talud',construccion:'Construcción',residuo:'Residuo / descarga',acceso:'Acceso',suelo:'Suelo',otro:'Otro'};
const checklist={general:['acceso','drenaje','vegetacion'],relleno:['relleno','drenaje','vegetacion'],cobertura:['desmonte','vegetacion','construccion'],drenaje:['drenaje','erosion','suelo'],vegetacion:['vegetacion','desmonte','suelo'],factibilidad:['acceso','drenaje','construccion']};

function Icon({name,size=18}){const paths={map:'M3 6.5 9 3l6 3.5L21 3v14.5L15 21l-6-3.5L3 21V6.5Zm6-3v14m6-11v14',plus:'M12 5v14M5 12h14',pin:'M12 21s7-5.2 7-12a7 7 0 1 0-14 0c0 6.8 7 12 7 12Zm0-9a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',camera:'M4 7h3l1.5-2h7L17 7h3v12H4V7Zm8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',route:'M5 5a2 2 0 1 0 0 .1V15a4 4 0 0 0 4 4h6a4 4 0 0 0 4-4V9m0 0a2 2 0 1 0 0-.1',layers:'m4 8 8-4 8 4-8 4-8-4Zm0 4 8 4 8-4M4 16l8 4 8-4',download:'M12 3v12m0 0 5-5m-5 5-5-5M5 21h14',check:'m5 12 4 4L19 6',x:'M6 6l12 12M18 6 6 18',chev:'m9 18 6-6-6-6',target:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-5a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',clock:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-13v5l3 2',signal:'M5 16a10 10 0 0 1 14 0M8 19a6 6 0 0 1 8 0M12 22h.01'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.map}/></svg>}

function useSync(){const[s,setS]=useState(()=>getSyncSnapshot());useEffect(()=>{const h=e=>setS(v=>({...v,...e.detail}));window.addEventListener('sltm-sync',h);pingApi();flushQueue();return()=>window.removeEventListener('sltm-sync',h)},[]);return s}
function useGps(active){const[gps,setGps]=useState(null),[error,setError]=useState(''),[history,setHistory]=useState([]);useEffect(()=>{if(!active)return;if(!navigator.geolocation){setError('Este dispositivo no expone geolocalización.');return}const id=navigator.geolocation.watchPosition(p=>{const q={lat:p.coords.latitude,lng:p.coords.longitude,alt:p.coords.altitude,altAcc:p.coords.altitudeAccuracy,acc:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading,at:now()};setGps(q);setHistory(v=>[...v.slice(-8),q]);setError('')},e=>setError(e.message),{enableHighAccuracy:true,maximumAge:500,timeout:20000});return()=>navigator.geolocation.clearWatch(id)},[active]);return{gps,error,stableAcc:median(history.slice(-5).map(p=>p.acc))}}
function useHeading(){const[heading,setHeading]=useState(null);useEffect(()=>{const h=e=>{const v=finite(e.webkitCompassHeading)?Number(e.webkitCompassHeading):finite(e.alpha)?(360-Number(e.alpha))%360:null;if(finite(v))setHeading(v)};window.addEventListener('deviceorientation',h,true);return()=>window.removeEventListener('deviceorientation',h,true)},[]);const request=async()=>{try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')await DeviceOrientationEvent.requestPermission()}catch{}};return{heading,request}}

function MapCanvas({terrains=[],selectedId,onSelect,gps,track=[],observations=[],follow=false,controls=true}){
 const host=useRef(null),map=useRef(null),layer=useRef(null),fitRef=useRef('');
 useEffect(()=>{const m=L.map(host.current,{zoomControl:false,attributionControl:true}).setView([23.2494,-106.4111],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(m);if(controls)L.control.zoom({position:'bottomright'}).addTo(m);layer.current=L.layerGroup().addTo(m);map.current=m;setTimeout(()=>m.invalidateSize(),80);return()=>m.remove()},[]);
 useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();const bounds=[];terrains.forEach(t=>{if(!Array.isArray(t.poly)||t.poly.length<3)return;const sel=t.id===selectedId;const p=L.polygon(t.poly,{color:sel?'#111613':'#516258',weight:sel?2.4:1.4,fillColor:sel?'#96aa9d':'#b6c2ba',fillOpacity:sel?.25:.12}).addTo(g);p.on('click',()=>onSelect?.(t.id));p.bindTooltip(`<b>${t.name||'Terreno'}</b><br>${fmt(t.area)} m²`);bounds.push(...t.poly)});if(track.length){L.polyline(track.map(p=>[p.lat,p.lng]),{color:'#111613',weight:3}).addTo(g);track.forEach((p,i)=>{if(i===0||i===track.length-1||i%10===0)L.circleMarker([p.lat,p.lng],{radius:3,color:'#111613',fillColor:'#fff',fillOpacity:1,weight:1}).addTo(g)})}observations.forEach(o=>{if(!finite(o.lat)||!finite(o.lng))return;const fill=o.severity==='alta'?'#b0463c':o.severity==='media'?'#9a7628':'#486652';L.circleMarker([o.lat,o.lng],{radius:6,color:'#fff',fillColor:fill,fillOpacity:1,weight:2}).bindTooltip(`${findingLabels[o.kind]||o.kind}${o.note?` · ${o.note}`:''}`).addTo(g)});if(gps){L.circle([gps.lat,gps.lng],{radius:gps.acc||0,color:'#5d7265',weight:1,fillOpacity:.025}).addTo(g);L.circleMarker([gps.lat,gps.lng],{radius:6,color:'#fff',fillColor:'#111613',fillOpacity:1,weight:2}).addTo(g);if(follow)m.setView([gps.lat,gps.lng],Math.max(m.getZoom(),17))}else if(bounds.length&&fitRef.current!==`${terrains.length}-${selectedId}`){fitRef.current=`${terrains.length}-${selectedId}`;m.fitBounds(bounds,{padding:[36,36],maxZoom:17})}},[terrains,selectedId,gps,track,observations,follow]);
 return <div ref={host} className="mf-map"/>
}

function StatusPill(){const s=useSync();const text=!s.online?'Offline':s.syncing?'Sincronizando':s.pending?`${s.pending} pendientes`:s.backend?'Sincronizado':'Conectando';return <div className={`mf-status ${!s.online?'offline':s.pending?'pending':''}`}><span></span>{text}</div>}

function Home({terrains,visits,selectedId,setSelectedId,onNew,onImport,onInspect}){
 const selected=terrains.find(t=>t.id===selectedId)||terrains[0]||null;
 const lastVisit=selected?[...visits].filter(v=>v.terrainId===selected.id).sort((a,b)=>String(b.endedAt||b.date).localeCompare(String(a.endedAt||a.date)))[0]:null;
 return <div className="mf-home">
  <section className="mf-map-shell"><MapCanvas terrains={terrains} selectedId={selected?.id} onSelect={setSelectedId}/>
   <div className="mf-map-topbar"><div><span className="mf-kicker">OPERACIÓN TERRITORIAL</span><h2>{terrains.length?'Inventario de campo':'Tu territorio empieza aquí'}</h2></div><div className="mf-map-actions"><button className="ghost" onClick={onImport}><Icon name="layers"/>Importar</button><button className="dark" onClick={onNew}><Icon name="plus"/>Nuevo terreno</button></div></div>
   {!terrains.length&&<div className="mf-empty-overlay"><div className="mf-empty-card"><div className="mf-iconbox"><Icon name="target" size={24}/></div><span>INVENTARIO VACÍO</span><h3>Registra el primer sitio con datos reales.</h3><p>Levanta vértices con el GPS del teléfono o importa un polígono GeoJSON que ya tengas.</p><div><button className="dark" onClick={onNew}>Levantar con celular</button><button className="ghost" onClick={onImport}>Importar GeoJSON</button></div></div></div>}
   {terrains.length>0&&<div className="mf-floating-list"><div className="mf-floating-head"><span>TERRENOS</span><b>{terrains.length}</b></div>{terrains.slice(0,6).map(t=><button key={t.id} className={t.id===selected?.id?'active':''} onClick={()=>setSelectedId(t.id)}><i></i><div><strong>{t.name}</strong><span>{fmt(t.area)} m² · {sourceLabel(t)}</span></div><Icon name="chev" size={15}/></button>)}</div>}
  </section>
  <aside className="mf-panel">{selected?<><div className="mf-panel-head"><span>{selected.id}</span><h2>{selected.name}</h2><p>{purposeLabels[selected.purpose]||selected.purpose||'Sin motivo especificado'}</p></div><div className="mf-metric-grid"><Metric label="Área" value={`${fmt(selected.area)} m²`}/><Metric label="Perímetro" value={finite(selected.perimeter)?`${Math.round(selected.perimeter)} m`:'—'}/><Metric label="Precisión mediana" value={finite(selected.sourceAccuracy?.median)?`±${Math.round(selected.sourceAccuracy.median)} m`:'—'}/><Metric label="Visitas" value={visits.filter(v=>v.terrainId===selected.id).length}/></div><section className="mf-insight"><span>ÚLTIMA EVIDENCIA</span>{lastVisit?<><strong>{lastVisit.date||'Visita de campo'}</strong><p>{lastVisit.points?.length||0} hallazgos · {lastVisit.evidence?.length||0} fotos · {Math.round(lastVisit.distance||0)} m recorridos.</p></>:<><strong>Sin inspecciones cerradas</strong><p>El terreno ya está registrado. La siguiente acción útil es documentar lo que existe físicamente en sitio.</p></>}</section><button className="mf-inspect" onClick={()=>onInspect(selected.id)}><div><Icon name="route"/><span><b>Nueva inspección</b><small>Recorrido + hallazgos + fotografías</small></span></div><Icon name="chev"/></button><div className="mf-data-note"><Icon name="signal" size={16}/><p><b>Fuente:</b> {sourceLabel(selected)}. SLTM conserva la precisión GNSS junto con la geometría; no la presenta como topografía certificada.</p></div></>:<div className="mf-side-empty"><span>SLTM</span><h3>Sin terreno seleccionado</h3><p>Crea o importa un terreno para empezar.</p></div>}</aside>
 </div>
}

function sourceLabel(t){return t.source==='geojson_import'?'GeoJSON':t.source==='gps_vertices'?'Vértices GPS':t.source==='gps_walk'?'Recorrido GPS':'Campo'}
function Metric({label,value}){return <div className="mf-metric"><span>{label}</span><strong>{value}</strong></div>}

function NewTerrainModal({onClose,onSaved}){
 const[step,setStep]=useState(1),[name,setName]=useState(''),[purpose,setPurpose]=useState('general'),[method,setMethod]=useState('vertices'),[note,setNote]=useState(''),[points,setPoints]=useState([]),[recording,setRecording]=useState(false),[paused,setPaused]=useState(false);const{gps,error,stableAcc}=useGps(step>=2);const last=useRef(null);
 useEffect(()=>{if(step!==3||method!=='walk'||!recording||paused||!gps)return;const moved=!last.current?Infinity:hav(last.current,gps),plausible=!last.current||moved<Math.max(80,(gps.acc||20)*4),speedOK=!finite(gps.speed)||Number(gps.speed)<12;if(gps.acc<=25&&plausible&&speedOK&&(!last.current||moved>=3)){last.current=gps;setPoints(v=>[...v,gps])}},[step,method,recording,paused,gps]);
 const poly=points.map(p=>[p.lat,p.lng]),area=poly.length>=3?polyArea(poly):0,perimeter=points.length>=3?polygonPerimeter(points):0,acc=median(points.map(p=>p.acc));
 const addVertex=()=>{if(!gps||gps.acc>25)return;const prev=points.at(-1);if(prev&&hav(prev,gps)<1.5)return;setPoints(v=>[...v,{...gps,vertex:true}])};
 const save=()=>{if(points.length<3||!name.trim())return;const id=uid('T'),terrain={id,name:name.trim(),purpose,note:note.trim(),status:'Activo',createdAt:now(),last:today(),poly,area,perimeter,center:[poly.reduce((s,p)=>s+p[0],0)/poly.length,poly.reduce((s,p)=>s+p[1],0)/poly.length],source:method==='vertices'?'gps_vertices':'gps_walk',sourceAccuracy:{median:acc,avg:points.length?points.reduce((s,p)=>s+(p.acc||0),0)/points.length:null,max:points.length?Math.max(...points.map(p=>p.acc||0)):null,points:points.length}};queueTerrain(terrain);onSaved(terrain)};
 return <div className="mf-modal"><div className={`mf-modal-card ${step===3?'capture':''}`}><header><div><span>NUEVO TERRENO</span><h2>{step===1?'Configura el levantamiento':step===2?'Verifica la señal GNSS':'Captura el límite físico'}</h2></div><button className="icon-btn" onClick={onClose}><Icon name="x"/></button></header><div className="mf-steps"><i className={step>=1?'done':''}></i><i className={step>=2?'done':''}></i><i className={step>=3?'done':''}></i></div>
 {step===1&&<div className="mf-form"><div className="two"><label>Nombre del sitio<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Predio junto al arroyo"/></label><label>Objetivo<select value={purpose} onChange={e=>setPurpose(e.target.value)}>{Object.entries(purposeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Contexto de campo<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Qué quieres verificar aquí"/></label><div className="mf-method"><button className={method==='vertices'?'active':''} onClick={()=>setMethod('vertices')}><Icon name="pin"/><div><b>Vértices GPS</b><span>Detente en cada esquina y registra el punto. Más control para una demo.</span></div></button><button className={method==='walk'?'active':''} onClick={()=>setMethod('walk')}><Icon name="route"/><div><b>Recorrido continuo</b><span>Camina el lindero y SLTM registra posiciones válidas automáticamente.</span></div></button></div><button className="dark wide" disabled={!name.trim()} onClick={()=>setStep(2)}>Continuar</button></div>}
 {step===2&&<div className="mf-gps-stage"><div className="mf-gps-map"><MapCanvas gps={gps} follow/></div><aside><span>PRECISIÓN ESTABILIZADA</span><strong>{finite(stableAcc)?`±${Math.round(stableAcc)} m`:gps?`±${Math.round(gps.acc)} m`:'—'}</strong><div className={`mf-quality ${finite(stableAcc??gps?.acc)&&(stableAcc??gps.acc)<=15?'good':(stableAcc??gps?.acc)<=25?'ok':'bad'}`}>{finite(stableAcc??gps?.acc)?(stableAcc??gps.acc)<=15?'Señal buena':(stableAcc??gps.acc)<=25?'Señal utilizable':'Señal débil':'Buscando señal'}</div><p>SLTM sólo habilita el levantamiento cuando la precisión reportada por el teléfono es ≤25 m.</p>{error&&<div className="mf-error">{error}</div>}<button className="dark wide" disabled={!gps||(stableAcc??gps.acc)>25} onClick={()=>{setPoints([]);last.current=null;setRecording(method==='walk');setStep(3)}}>Entrar al levantamiento</button></aside></div>}
 {step===3&&<div className="mf-capture-stage"><div className="mf-capture-map"><MapCanvas gps={gps} track={points} follow/></div><div className="mf-capture-dock"><div className="mf-live-metrics"><Metric label="Área" value={area?`${fmt(area)} m²`:'—'}/><Metric label="Perímetro" value={perimeter?`${Math.round(perimeter)} m`:'—'}/><Metric label={method==='vertices'?'Vértices':'Puntos'} value={points.length}/><Metric label="Precisión mediana" value={finite(acc)?`±${Math.round(acc)} m`:'—'}/></div><div className="mf-capture-message">{!gps?'Esperando GPS…':gps.acc>25?'La posición actual es débil y no debe registrarse.':method==='vertices'?'Colócate físicamente en una esquina o cambio de dirección y registra un vértice.':paused?'Recorrido pausado.':'Camina por el lindero; SLTM filtra posiciones débiles o saltos poco plausibles.'}</div><div className="mf-capture-buttons">{method==='vertices'?<><button className="dark big" disabled={!gps||gps.acc>25} onClick={addVertex}><Icon name="pin"/>Registrar vértice</button><button className="ghost" disabled={!points.length} onClick={()=>setPoints(v=>v.slice(0,-1))}>Deshacer</button></>:<><button className="dark big" onClick={()=>setPaused(v=>!v)}>{paused?'Reanudar':'Pausar recorrido'}</button><button className="ghost" disabled={!points.length} onClick={()=>{setPoints(v=>v.slice(0,-1));last.current=null}}>Quitar último</button></>}<button className="accent" disabled={points.length<3} onClick={save}><Icon name="check"/>Guardar terreno</button></div><small>El polígono es inventario territorial preliminar. La precisión GNSS queda documentada en el expediente.</small></div></div>}
 </div></div>
}

function InspectionMode({terrain,onClose,onFinished}){
 const[active,setActive]=useState(false),[track,setTrack]=useState([]),[points,setPoints]=useState([]),[evidence,setEvidence]=useState([]),[kind,setKind]=useState((checklist[terrain.purpose]||['otro'])[0]),[severity,setSeverity]=useState('media'),[note,setNote]=useState('');const{gps,error,stableAcc}=useGps(active);const{heading,request}=useHeading();const last=useRef(null);const started=useRef(null);
 useEffect(()=>{const d=read(DRAFT_KEY,null);if(d?.terrainId===terrain.id){setTrack(d.track||[]);setPoints(d.points||[]);setEvidence(d.evidence||[])}},[terrain.id]);
 useEffect(()=>{if(active||track.length||points.length||evidence.length)write(DRAFT_KEY,{terrainId:terrain.id,track,points,evidence,savedAt:now()})},[active,terrain.id,track,points,evidence]);
 useEffect(()=>{if(!active||!gps)return;const moved=!last.current?Infinity:hav(last.current,gps),plausible=!last.current||moved<Math.max(80,(gps.acc||20)*4);if(gps.acc<=30&&plausible&&(!last.current||moved>=4)){last.current=gps;setTrack(v=>[...v,gps])}},[active,gps]);
 const begin=async()=>{await request();started.current=now();setActive(true)};
 const addObservation=(withPhoto=false)=>{if(!gps)return;const o={id:uid('O'),kind,severity,note:note.trim(),lat:gps.lat,lng:gps.lng,alt:gps.alt,acc:gps.acc,heading,at:now()};setPoints(v=>[...v,o]);setNote('');return o};
 const addPhoto=async e=>{const f=e.target.files?.[0];if(!f)return;const o=addObservation(true);const id=uid('E');await saveMedia(id,f);setEvidence(v=>[...v,{id,at:now(),gps:{...gps,heading},kind,severity,observationId:o?.id||null}]);e.target.value=''};
 const required=checklist[terrain.purpose]||[];const covered=new Set(points.map(p=>p.kind));const missing=required.filter(x=>!covered.has(x));const dist=routeDistance(track);const acc=median(track.map(p=>p.acc));
 const quality=Math.min(100,(finite(acc)&&acc<=15?30:finite(acc)&&acc<=25?20:10)+Math.min(points.length*10,30)+Math.min(evidence.length*15,30)+(dist>=30?10:0));
 const finish=()=>{const visit={id:uid('V'),terrainId:terrain.id,date:today(),startedAt:started.current||track[0]?.at||now(),endedAt:now(),mode:'inspection',purpose:terrain.purpose,track,points,evidence,distance:dist,avgAcc:track.length?track.reduce((s,p)=>s+(p.acc||0),0)/track.length:null,medianAcc:acc,quality};queueVisitBundle(terrain.id,visit);localStorage.removeItem(DRAFT_KEY);onFinished(visit)};
 return <div className="mf-operation"><header><button className="mf-back" onClick={onClose}>← Inventario</button><div><span>INSPECCIÓN ACTIVA</span><h2>{terrain.name}</h2></div><div className="mf-operation-status"><i className={active?'on':''}></i>{active?`GPS ±${gps?Math.round(gps.acc):'—'} m`:'Lista para iniciar'}</div></header><div className="mf-operation-body"><section className="mf-op-map"><MapCanvas terrains={[terrain]} selectedId={terrain.id} gps={gps} track={track} observations={points} follow={active}/>{!active&&<div className="mf-start-card"><span>{purposeLabels[terrain.purpose]||'Inspección'}</span><h3>Documenta lo que realmente existe en sitio.</h3><p>El recorrido, los hallazgos y las fotografías quedarán vinculados a este terreno.</p><button className="dark big" onClick={begin}><Icon name="route"/>Iniciar inspección</button></div>}</section><aside className="mf-op-panel"><div className="mf-op-summary"><Metric label="Recorrido" value={`${Math.round(dist)} m`}/><Metric label="Hallazgos" value={points.length}/><Metric label="Fotos" value={evidence.length}/><Metric label="Precisión" value={finite(acc)?`±${Math.round(acc)} m`:'—'}/></div><div className="mf-guidance"><span>SIGUIENTE PASO</span><strong>{!active?'Inicia la inspección':!gps?'Esperando posición':gps.acc>25?'Espera una señal más estable':missing.length?`Documenta: ${findingLabels[missing[0]]}`:evidence.length<2?'Añade evidencia fotográfica':'La visita ya tiene cobertura básica'}</strong><p>{missing.length?`Checklist pendiente: ${missing.map(x=>findingLabels[x]).join(' · ')}`:'Checklist del objetivo cubierto.'}</p></div>{active&&<><div className="mf-findings"><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(findingLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Relevancia<div className="mf-severity">{['baja','media','alta'].map(s=><button key={s} className={severity===s?'active':''} onClick={()=>setSeverity(s)}>{s}</button>)}</div></label><label>Descripción<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe exactamente qué estás viendo"/></label></div><div className="mf-op-actions"><button className="ghost" disabled={!gps} onClick={()=>addObservation(false)}><Icon name="pin"/>Guardar hallazgo</button><label className="dark"><Icon name="camera"/>Foto + punto<input type="file" accept="image/*" capture="environment" onChange={addPhoto}/></label></div></>}{points.length>0&&<div className="mf-recent"><span>ÚLTIMOS HALLAZGOS</span>{points.slice(-4).reverse().map(p=><div key={p.id}><i className={p.severity}></i><div><b>{findingLabels[p.kind]}</b><small>{p.note||'Sin descripción'} · ±{Math.round(p.acc)} m</small></div></div>)}</div>}{active&&<button className="accent wide close-visit" onClick={finish}><Icon name="check"/>Cerrar visita y generar ficha</button>}{error&&<div className="mf-error">{error}</div>}</aside></div></div>
}

function ImportModal({onClose,onImported}){const[fileName,setFileName]=useState(''),[preview,setPreview]=useState([]),[error,setError]=useState('');const parse=async f=>{setError('');setFileName(f.name);try{const j=JSON.parse(await f.text()),features=j.type==='FeatureCollection'?j.features:j.type==='Feature'?[j]:[];const out=[];features.forEach((f,i)=>{if(f.geometry?.type!=='Polygon')return;const ring=f.geometry.coordinates?.[0]||[];const poly=ring.slice(0,-1).map(([lng,lat])=>[Number(lat),Number(lng)]).filter(p=>finite(p[0])&&finite(p[1]));if(poly.length<3)return;const pts=poly.map(([lat,lng])=>({lat,lng})),id=uid('T');out.push({id,name:f.properties?.name||f.properties?.nombre||`Terreno importado ${i+1}`,purpose:'general',status:'Activo',createdAt:now(),last:today(),poly,area:polyArea(poly),perimeter:polygonPerimeter(pts),center:[poly.reduce((s,p)=>s+p[0],0)/poly.length,poly.reduce((s,p)=>s+p[1],0)/poly.length],source:'geojson_import',sourceAccuracy:{note:'Geometría importada; precisión depende de la fuente original'}})});if(!out.length)throw new Error('No encontré polígonos válidos');setPreview(out)}catch(e){setError(e.message);setPreview([])}};const commit=()=>{preview.forEach(queueTerrain);onImported(preview)};return <div className="mf-modal"><div className="mf-modal-card import"><header><div><span>IMPORTAR GEOMETRÍA</span><h2>Trae un polígono existente</h2></div><button className="icon-btn" onClick={onClose}><Icon name="x"/></button></header><div className="mf-import-body"><label className="mf-drop"><Icon name="layers" size={24}/><b>{fileName||'Selecciona un archivo GeoJSON'}</b><span>FeatureCollection o Feature con geometría Polygon</span><input type="file" accept=".geojson,.json,application/geo+json,application/json" onChange={e=>e.target.files?.[0]&&parse(e.target.files[0])}/></label>{error&&<div className="mf-error">{error}</div>}{preview.length>0&&<div className="mf-import-preview"><span>{preview.length} terreno(s) listos</span>{preview.slice(0,5).map(t=><div key={t.id}><b>{t.name}</b><small>{fmt(t.area)} m²</small></div>)}<button className="dark wide" onClick={commit}>Importar al inventario</button></div>}</div></div></div>}

function VisitSummary({terrain,visit,onDone}){const counts=useMemo(()=>visit.points.reduce((a,p)=>(a[p.kind]=(a[p.kind]||0)+1,a),{}),[visit]);return <div className="mf-summary-page"><div className="mf-summary-card"><div className="mf-summary-top"><div><span>VISITA CERRADA</span><h2>{terrain.name}</h2><p>{new Date(visit.endedAt).toLocaleString('es-MX')}</p></div><div className="mf-score"><small>CALIDAD</small><strong>{visit.quality}</strong><span>/100</span></div></div><div className="mf-summary-map"><MapCanvas terrains={[terrain]} selectedId={terrain.id} track={visit.track} observations={visit.points}/></div><div className="mf-summary-metrics"><Metric label="Recorrido" value={`${Math.round(visit.distance)} m`}/><Metric label="Hallazgos" value={visit.points.length}/><Metric label="Fotografías" value={visit.evidence.length}/><Metric label="Precisión mediana" value={finite(visit.medianAcc)?`±${Math.round(visit.medianAcc)} m`:'—'}/></div>{Object.keys(counts).length>0&&<div className="mf-summary-findings"><span>HALLAZGOS REGISTRADOS</span>{Object.entries(counts).map(([k,v])=><div key={k}><b>{findingLabels[k]||k}</b><strong>{v}</strong></div>)}</div>}<div className="mf-summary-actions"><button className="dark" onClick={()=>window.print()}>Imprimir ficha</button><button className="ghost" onClick={onDone}>Volver al inventario</button></div></div></div>}

export default function ModernFieldApp(){
 const[terrains,setTerrains]=useState(()=>read(TERRAIN_STORE,[])),[visits,setVisits]=useState(()=>read(VISIT_STORE,[])),[selectedId,setSelectedId]=useState(null),[mode,setMode]=useState('home'),[lastVisit,setLastVisit]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>write(TERRAIN_STORE,terrains),[terrains]);useEffect(()=>write(VISIT_STORE,visits),[visits]);
 useEffect(()=>{(async()=>{try{const r=await pullWorkspace();if(r.terrains?.length){setTerrains(local=>{const m=new Map(local.map(t=>[t.id,t]));r.terrains.forEach(t=>m.set(t.id,{...m.get(t.id),...t}));return[...m.values()]})}if(r.visits?.length){setVisits(local=>{const m=new Map(local.map(v=>[v.id,v]));r.visits.forEach(v=>m.set(v.id,{...m.get(v.id),...v}));return[...m.values()]})}}catch{}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!selectedId&&terrains.length)setSelectedId(terrains[0].id)},[terrains,selectedId]);
 const selected=terrains.find(t=>t.id===selectedId)||null;
 const addTerrain=t=>{setTerrains(v=>[...v.filter(x=>x.id!==t.id),t]);setSelectedId(t.id);setMode('home')};
 const addImported=xs=>{setTerrains(v=>{const m=new Map(v.map(t=>[t.id,t]));xs.forEach(t=>m.set(t.id,t));return[...m.values()]});setSelectedId(xs[0]?.id||null);setMode('home')};
 const closeVisit=v=>{setVisits(xs=>[...xs.filter(x=>x.id!==v.id),{...v,terrainId:selectedId}]);setLastVisit(v);setMode('summary')};
 return <div className="mf-app"><aside className="mf-sidebar"><div className="mf-brand"><div>SL</div><span>SLTM</span></div><nav><button className={mode==='home'?'active':''} onClick={()=>setMode('home')}><Icon name="map"/><span>Inventario</span></button><button onClick={()=>setMode('new')}><Icon name="plus"/><span>Nuevo</span></button>{exportGeoJsonUrl()&&<a href={exportGeoJsonUrl()} target="_blank" rel="noreferrer"><Icon name="download"/><span>Exportar</span></a>}</nav><div className="mf-sidebar-bottom"><StatusPill/></div></aside><main className="mf-main"><header className="mf-header"><div><span className="mf-kicker">SISTEMA DE LEVANTAMIENTO TERRITORIAL MÓVIL</span><h1>{mode==='home'?'Territorio':mode==='new'?'Nuevo terreno':mode==='import'?'Importar':mode==='inspect'?'Inspección':'Ficha de visita'}</h1></div><div className="mf-header-actions"><span>{terrains.length} terrenos · {visits.length} visitas</span>{mode==='home'&&<button className="dark" onClick={()=>setMode('new')}><Icon name="plus"/>Nuevo terreno</button>}</div></header><div className="mf-content">{loading?<div className="mf-loading">Sincronizando inventario…</div>:<>{mode==='home'&&<Home terrains={terrains} visits={visits} selectedId={selectedId} setSelectedId={setSelectedId} onNew={()=>setMode('new')} onImport={()=>setMode('import')} onInspect={id=>{setSelectedId(id);setMode('inspect')}}/>}{mode==='new'&&<NewTerrainModal onClose={()=>setMode('home')} onSaved={addTerrain}/>} {mode==='import'&&<ImportModal onClose={()=>setMode('home')} onImported={addImported}/>} {mode==='inspect'&&selected&&<InspectionMode terrain={selected} onClose={()=>setMode('home')} onFinished={closeVisit}/>} {mode==='summary'&&selected&&lastVisit&&<VisitSummary terrain={selected} visit={lastVisit} onDone={()=>setMode('home')}/>}</>}</div></main></div>
}
