import React,{useEffect,useMemo,useRef,useState}from'react';
import L from'leaflet';
import'leaflet/dist/leaflet.css';
import'./terrain-inventory.css';
import{saveMedia,getMedia}from'./mediaDb';

const STORE='sltm_terrain_inventory_v2';
const today=()=>new Date().toISOString().slice(0,10);
const fmt=n=>new Intl.NumberFormat('es-MX',{maximumFractionDigits:0}).format(Number(n)||0);
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const hav=(a,b)=>{const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const polyArea=ll=>{if(ll.length<3)return 0;const lat0=ll.reduce((s,p)=>s+p[0],0)/ll.length*Math.PI/180,pts=ll.map(([lat,lng])=>({x:lng*111320*Math.cos(lat0),y:lat*110540}));let a=0;pts.forEach((p,i)=>{const q=pts[(i+1)%pts.length];a+=p.x*q.y-q.x*p.y});return Math.abs(a)/2};
const routeDistance=pts=>pts.slice(1).reduce((s,p,i)=>s+hav(pts[i],p),0);

const DEMO=[
{id:'T-001',name:'Predio Estero Norte',status:'Monitoreo',use:'Mixto',area:12840,slope:3.8,permeable:72,built:8,access:82,change:14,last:'2026-09-08',center:[23.2665,-106.4215],poly:[[23.2671,-106.4224],[23.2672,-106.4208],[23.2661,-106.4205],[23.2658,-106.4220]],tags:['humedal cercano','relleno observado'],drainage:72,vegetation:76,fill:22,visits:[]},
{id:'T-002',name:'Lote Marina Oriente',status:'Disponible',use:'Urbano',area:7420,slope:1.9,permeable:41,built:0,access:94,change:3,last:'2026-09-02',center:[23.2588,-106.4109],poly:[[23.2593,-106.4117],[23.2594,-106.4103],[23.2583,-106.4102],[23.2581,-106.4114]],tags:['frente vial','sin construcción'],drainage:54,vegetation:32,fill:8,visits:[]},
{id:'T-003',name:'Reserva Cerritos',status:'Revisión',use:'Borde urbano',area:21400,slope:6.4,permeable:91,built:2,access:63,change:22,last:'2026-09-11',center:[23.3034,-106.4781],poly:[[23.3042,-106.4791],[23.3044,-106.4770],[23.3026,-106.4767],[23.3024,-106.4788]],tags:['vegetación','cambio reciente'],drainage:81,vegetation:93,fill:16,visits:[]},
{id:'T-004',name:'Plataforma Sur',status:'En obra',use:'Industrial',area:9650,slope:2.5,permeable:18,built:27,access:88,change:37,last:'2026-09-12',center:[23.1968,-106.4017],poly:[[23.1975,-106.4025],[23.1973,-106.4007],[23.1961,-106.4009],[23.1960,-106.4024]],tags:['relleno','plataforma'],drainage:38,vegetation:12,fill:68,visits:[]},
{id:'T-005',name:'Predio Arroyo Seco',status:'Monitoreo',use:'Periurbano',area:15600,slope:8.7,permeable:84,built:5,access:58,change:9,last:'2026-08-28',center:[23.2441,-106.3657],poly:[[23.2450,-106.3667],[23.2448,-106.3648],[23.2432,-106.3649],[23.2430,-106.3666]],tags:['escurrimiento','talud'],drainage:88,vegetation:69,fill:10,visits:[]}
];

function enrich(t){
 const ecoPriority=Math.round(clamp((100-t.permeable)*.22+t.change*.32+t.fill*.18+t.drainage*.12+t.vegetation*.06+Math.min(t.slope*4,100)*.10));
 const feasibility=Math.round(clamp(t.access*.32+(100-Math.min(t.slope*6,100))*.22+(100-t.fill)*.13+(100-t.change)*.09+(100-Math.max(0,t.drainage-60))*.08+(100-Math.max(0,t.built-45))*.16));
 const latest=t.visits?.[t.visits.length-1],conf=Math.round(clamp((latest?45:15)+(latest?.points?.length||0)*3+(latest?.evidence?.length||0)*8+(latest?.avgAcc&&latest.avgAcc<10?18:latest?.avgAcc<20?10:0)));
 return{...t,ecoPriority,feasibility,confidence:conf};
}
function actions(t){const a=[];
 if(t.change>=20)a.push({tone:'urgent',title:'Verificar cambio reciente',why:`Cambio registrado ${t.change}%`,task:'Recorrer perímetro y documentar superficies alteradas.'});
 if(t.fill>=35)a.push({tone:'urgent',title:'Revisar relleno / modificación de cota',why:`Relleno observado ${t.fill}/100`,task:'Registrar puntos de suelo y perfil altimétrico indicativo.'});
 if(t.drainage>=70)a.push({tone:'eco',title:'Caracterizar escurrimiento',why:`Sensibilidad de drenaje ${t.drainage}/100`,task:'Marcar puntos bajos, cauces visibles y dirección de escurrimiento.'});
 if(t.permeable<35)a.push({tone:'eco',title:'Cuantificar impermeabilización',why:`Sólo ${t.permeable}% permeable`,task:'Delimitar pavimento, construcción y suelo expuesto.'});
 if(t.feasibility>=75)a.push({tone:'dev',title:'Levantamiento de oportunidad',why:`Factibilidad física ${t.feasibility}/100`,task:'Confirmar accesos, pendiente, obstáculos y superficie útil.'});
 if(t.confidence<55)a.push({tone:'neutral',title:'Elevar confianza del expediente',why:`Confianza ${t.confidence}/100`,task:'Completar una visita con ≥6 puntos y evidencia fotográfica.'});
 return a.slice(0,3)}

function MapPanel({terrains,selectedId,onSelect,onCreate,metric='status',track=[],allowDraw=true}){
 const host=useRef(null),mapRef=useRef(null),terrainLayer=useRef(null),trackLayer=useRef(null),drawPts=useRef([]),drawing=useRef(false),temp=useRef(null);
 useEffect(()=>{const m=L.map(host.current,{zoomControl:false}).setView([23.2494,-106.4111],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(m);L.control.zoom({position:'bottomright'}).addTo(m);terrainLayer.current=L.layerGroup().addTo(m);trackLayer.current=L.layerGroup().addTo(m);mapRef.current=m;const click=e=>{if(!drawing.current)return;drawPts.current.push([e.latlng.lat,e.latlng.lng]);renderTemp()};m.on('click',click);return()=>m.remove()},[]);
 const renderTemp=()=>{const m=mapRef.current;if(temp.current)m.removeLayer(temp.current);if(drawPts.current.length)temp.current=L.polygon(drawPts.current,{color:'#111',weight:2,dashArray:'6 6',fillOpacity:.05}).addTo(m)};
 useEffect(()=>{const g=terrainLayer.current;if(!g)return;g.clearLayers();terrains.forEach(t=>{const sel=t.id===selectedId;let fill='#bfc8c1';if(metric==='eco')fill=t.ecoPriority>=60?'#7c9181':t.ecoPriority>=35?'#b8c6ba':'#dde4de';if(metric==='dev')fill=t.feasibility>=75?'#878b7c':t.feasibility>=55?'#b7b7aa':'#deddd5';const p=L.polygon(t.poly,{color:sel?'#101310':'#59625c',weight:sel?3:1.3,fillColor:fill,fillOpacity:sel?.45:.28}).addTo(g);p.on('click',()=>onSelect(t.id));p.bindTooltip(`<b>${t.id}</b> · ${t.name}<br>${fmt(t.area)} m² · Eco ${t.ecoPriority} · Des ${t.feasibility}`)})},[terrains,selectedId,metric]);
 useEffect(()=>{const g=trackLayer.current;if(!g)return;g.clearLayers();if(track.length>1)L.polyline(track.map(p=>[p.lat,p.lng]),{color:'#171b18',weight:3}).addTo(g);if(track.length)L.circleMarker([track.at(-1).lat,track.at(-1).lng],{radius:5,color:'#fff',weight:2,fillColor:'#111',fillOpacity:1}).addTo(g)},[track]);
 const begin=()=>{drawing.current=true;drawPts.current=[];renderTemp()};const close=()=>{if(drawPts.current.length<3)return;const poly=[...drawPts.current];onCreate(poly,polyArea(poly));drawing.current=false;drawPts.current=[];renderTemp()};
 return <div className="map-wrap"><div ref={host} className="map"/>{allowDraw&&<div className="map-actions"><button onClick={begin}>+ Delimitar terreno</button><button onClick={close}>Cerrar polígono</button></div>}</div>
}

function Matrix({terrains,onSelect}){return <div className="matrix"><div className="matrix-y">prioridad ecológica ↑</div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="50" y1="0" x2="50" y2="100"/><line x1="0" y1="50" x2="100" y2="50"/>{terrains.map(t=><g key={t.id} onClick={()=>onSelect(t.id)}><circle cx={t.feasibility} cy={100-t.ecoPriority} r="3"/><title>{t.name}</title></g>)}</svg><div className="matrix-x">factibilidad física →</div><div className="quad q1">desarrollo + vigilancia</div><div className="quad q2">conservación / revisión</div><div className="quad q3">baja prioridad</div><div className="quad q4">oportunidad física</div></div>}

function FieldMission({terrain,onFinish}){
 const [active,setActive]=useState(false),[gps,setGps]=useState(null),[track,setTrack]=useState([]),[points,setPoints]=useState([]),[kind,setKind]=useState('borde'),[note,setNote]=useState(''),[evidence,setEvidence]=useState([]),[err,setErr]=useState(''),[surveyMode,setSurveyMode]=useState('inspeccion'),[heading,setHeading]=useState(null);const watch=useRef(null),last=useRef(null);const plan=actions(terrain);
 useEffect(()=>{const h=e=>setHeading(Number.isFinite(e.webkitCompassHeading)?e.webkitCompassHeading:Number.isFinite(e.alpha)?(360-e.alpha)%360:null);window.addEventListener('deviceorientation',h,true);return()=>{window.removeEventListener('deviceorientation',h,true);if(watch.current!=null)navigator.geolocation?.clearWatch(watch.current)}},[]);
 const requestOrientation=async()=>{try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')await DeviceOrientationEvent.requestPermission()}catch{}}
 const start=async()=>{if(!navigator.geolocation){setErr('Geolocalización no disponible');return}await requestOrientation();setErr('');setActive(true);watch.current=navigator.geolocation.watchPosition(p=>{const q={lat:p.coords.latitude,lng:p.coords.longitude,alt:p.coords.altitude,altAcc:p.coords.altitudeAccuracy,acc:p.coords.accuracy,heading,at:new Date().toISOString()};setGps(q);if(!last.current||hav(last.current,q)>=3){last.current=q;setTrack(v=>[...v,q])}},e=>setErr(e.message),{enableHighAccuracy:true,maximumAge:1000,timeout:20000})};
 const add=()=>{if(!gps)return;setPoints(v=>[...v,{...gps,heading,kind,note}]);setNote('')};
 const photo=async e=>{const f=e.target.files?.[0];if(!f)return;const id=`ev-${terrain.id}-${Date.now()}`;await saveMedia(id,f);setEvidence(v=>[...v,{id,name:f.name||'foto',at:new Date().toISOString(),gps:{...gps,heading}}]);e.target.value=''};
 const distance=routeDistance(track),closure=track.length>2?hav(track[0],track.at(-1)):null,perimeterArea=surveyMode==='perimetro'&&track.length>=4?polyArea(track.map(p=>[p.lat,p.lng])):null,closeRatio=closure!=null&&distance>0?closure/distance:null;
 const currentQuality=useMemo(()=>{let q=0;if(gps?.acc<=8)q+=35;else if(gps?.acc<=20)q+=22;else if(gps)q+=10;q+=Math.min(points.length*6,30);q+=Math.min(evidence.length*10,20);if(surveyMode==='perimetro'&&closeRatio!=null&&closeRatio<.08)q+=15;else if(surveyMode==='inspeccion'&&distance>20)q+=15;return Math.round(clamp(q))},[gps,points.length,evidence.length,surveyMode,closeRatio,distance]);
 const nextPrompt=useMemo(()=>{if(!active)return'Inicia el levantamiento para activar guía de campo.';if(!gps)return'Esperando posición GNSS…';if(gps.acc>25)return'Precisión baja: espera unos segundos o busca cielo abierto.';if(surveyMode==='perimetro'&&distance<20)return'Recorre el lindero; el sistema traza tu perímetro automáticamente.';if(surveyMode==='perimetro'&&closeRatio!=null&&closeRatio>.12)return'Acércate al punto de inicio para cerrar mejor el perímetro.';if(points.length<3)return'Registra al menos 3 observaciones clasificadas.';if(evidence.length<2)return'Toma 2 fotografías desde puntos distintos para documentar el sitio.';return'Captura suficiente para cerrar una primera visita.'},[active,gps,surveyMode,distance,closeRatio,points.length,evidence.length]);
 const finish=()=>{if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setActive(false);const accs=track.map(p=>p.acc).filter(Number.isFinite),alts=track.map(p=>p.alt).filter(Number.isFinite);const summary={id:`V-${Date.now()}`,date:today(),mode:surveyMode,points,evidence,track,distance,closure,avgAcc:accs.length?accs.reduce((a,b)=>a+b,0)/accs.length:null,altRange:alts.length?Math.max(...alts)-Math.min(...alts):null,walkedArea:perimeterArea,quality:currentQuality};onFinish(summary);setTrack([]);setPoints([]);setEvidence([]);last.current=null};
 const q=gps?.acc<=8?'alta':gps?.acc<=20?'media':gps?'baja':'—';
 return <div className="mission-shell"><div className="mission-main"><div className="mission-title"><div><span>MISIÓN DE CAMPO</span><h2>{terrain.name}</h2><p>{nextPrompt}</p></div><b className={`quality ${q}`}>GPS {gps?`±${Math.round(gps.acc)} m`:'—'}</b></div><div className="mode-strip"><button className={surveyMode==='inspeccion'?'active':''} onClick={()=>!active&&setSurveyMode('inspeccion')}>Inspección</button><button className={surveyMode==='perimetro'?'active':''} onClick={()=>!active&&setSurveyMode('perimetro')}>Perímetro</button><span>Calidad actual <b>{currentQuality}/100</b></span></div><MapPanel terrains={[terrain]} selectedId={terrain.id} onSelect={()=>{}} onCreate={()=>{}} track={track} allowDraw={false}/><div className="field-console"><div className="console-kpis"><K label="Recorrido" value={`${distance.toFixed(0)} m`}/><K label="Puntos" value={points.length}/><K label="Evidencias" value={evidence.length}/><K label={surveyMode==='perimetro'?'Área indicativa':'Cota'} value={surveyMode==='perimetro'&&perimeterArea?`${fmt(perimeterArea)} m²`:Number.isFinite(gps?.alt)?`${gps.alt.toFixed(1)} m`:'—'}/></div>{err&&<div className="error">{err}</div>}{!active?<button className="primary big" onClick={start}>Iniciar levantamiento</button>:<><div className="capture-row"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="borde">Borde / lindero</option><option value="suelo">Suelo</option><option value="construcción">Construcción</option><option value="vegetación">Vegetación</option><option value="drenaje">Drenaje / punto bajo</option><option value="relleno">Relleno / corte</option><option value="acceso">Acceso</option></select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Observación breve"/><button onClick={add} disabled={!gps}>+ Punto</button><label className="camera-file">+ Foto<input type="file" accept="image/*" capture="environment" onChange={photo}/></label><button className="primary" onClick={finish}>Cerrar visita</button></div><div className="live-hint">{surveyMode==='perimetro'?'El área se estima únicamente como apoyo operativo a partir del recorrido GNSS; no sustituye deslinde o topografía.':'El recorrido se registra automáticamente cada ~3 m. Los puntos manuales son observaciones clasificadas.'}</div></>}</div></div><aside className="mission-side"><h3>Objetivos sugeridos</h3>{plan.map((a,i)=><div className={`action ${a.tone}`} key={i}><span>0{i+1}</span><strong>{a.title}</strong><p>{a.why}</p><em>{a.task}</em></div>)}<h3>Control de calidad</h3><div className="quality-list"><div><span>Precisión actual</span><b>{gps?`±${Math.round(gps.acc)} m`:'—'}</b></div><div><span>Cierre de recorrido</span><b>{closure!=null?`${closure.toFixed(0)} m`:'—'}</b></div><div><span>Rumbo del teléfono</span><b>{Number.isFinite(heading)?`${Math.round(heading)}°`:'—'}</b></div><div><span>Calidad de visita</span><b>{currentQuality}/100</b></div></div></aside></div>
}

export default function TerrainInventory(){
 const [terrains,setTerrains]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORE))||DEMO}catch{return DEMO}}),[selectedId,setSelectedId]=useState('T-001'),[tab,setTab]=useState('resumen'),[query,setQuery]=useState(''),[metric,setMetric]=useState('eco');
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify(terrains)),[terrains]);
 const data=useMemo(()=>terrains.map(enrich),[terrains]),selected=data.find(t=>t.id===selectedId)||data[0],filtered=data.filter(t=>(t.name+t.id+t.use+t.status+t.tags.join(' ')).toLowerCase().includes(query.toLowerCase()));
 const createTerrain=(poly,area)=>{const id=`T-${String(terrains.length+1).padStart(3,'0')}`,center=[poly.reduce((s,p)=>s+p[0],0)/poly.length,poly.reduce((s,p)=>s+p[1],0)/poly.length];const t={id,name:`Nuevo terreno ${id}`,status:'Pendiente',use:'Sin clasificar',area,slope:0,permeable:100,built:0,access:50,change:0,last:today(),center,poly,tags:['nuevo'],drainage:30,vegetation:50,fill:0,visits:[]};setTerrains(v=>[...v,t]);setSelectedId(id);setTab('inventario')};
 const patch=(k,v)=>setTerrains(xs=>xs.map(t=>t.id===selected.id?{...t,[k]:v}:t));
 const finishVisit=v=>setTerrains(xs=>xs.map(t=>t.id===selected.id?{...t,last:v.date,status:'Monitoreo',visits:[...(t.visits||[]),v]}:t));
 const openEvidence=async id=>{const m=await getMedia(id);if(!m)return;window.open(URL.createObjectURL(m.blob),'_blank','noopener,noreferrer')};
 const reset=()=>{localStorage.removeItem(STORE);setTerrains(DEMO);setSelectedId('T-001');setTab('resumen')};
 const urgent=[...data].sort((a,b)=>(b.ecoPriority+b.change)-(a.ecoPriority+a.change));
 return <div className="app-v2"><header className="top"><div><span className="eyebrow">SLTM · INVENTARIO DE TERRENOS</span><h1>Territorio observable</h1><p>Inventario, misión de campo y seguimiento con una sola ficha física del predio.</p></div><div className="top-status"><span>{data.length} terrenos</span><span>{data.reduce((s,t)=>s+(t.visits?.length||0),0)} visitas</span><button onClick={reset}>Reiniciar demo</button></div></header><nav className="nav"><button className={tab==='resumen'?'active':''} onClick={()=>setTab('resumen')}>Resumen</button><button className={tab==='inventario'?'active':''} onClick={()=>setTab('inventario')}>Inventario</button><button className={tab==='campo'?'active':''} onClick={()=>setTab('campo')}>Campo</button><button className={tab==='acciones'?'active':''} onClick={()=>setTab('acciones')}>Prioridades</button><button className={tab==='historial'?'active':''} onClick={()=>setTab('historial')}>Historial</button></nav>
 {tab==='resumen'&&<main className="overview"><section className="overview-map"><div className="section-head"><div><span>LECTURA TERRITORIAL</span><h2>¿Dónde conviene mirar primero?</h2></div><div className="metric-toggle"><button className={metric==='eco'?'active':''} onClick={()=>setMetric('eco')}>Prioridad ecológica</button><button className={metric==='dev'?'active':''} onClick={()=>setMetric('dev')}>Factibilidad física</button></div></div><MapPanel terrains={data} selectedId={selectedId} onSelect={id=>setSelectedId(id)} onCreate={createTerrain} metric={metric}/></section><aside className="overview-side"><div className="summary-kpis"><K label="Superficie inventariada" value={`${fmt(data.reduce((s,t)=>s+t.area,0)/10000)} ha`}/><K label="Alta prioridad eco" value={data.filter(t=>t.ecoPriority>=60).length}/><K label="Alta factibilidad" value={data.filter(t=>t.feasibility>=75).length}/><K label="Sin visita cerrada" value={data.filter(t=>!(t.visits?.length)).length}/></div><h3>Matriz de decisión</h3><Matrix terrains={data} onSelect={id=>{setSelectedId(id);setTab('inventario')}}/><h3>Siguiente acción</h3><div className="next-action"><span>{selected.id}</span><strong>{actions(selected)[0]?.title||'Completar expediente'}</strong><p>{actions(selected)[0]?.task}</p><button className="primary" onClick={()=>setTab('campo')}>Abrir misión</button></div></aside></main>}
 {tab==='inventario'&&<main className="inventory-layout"><aside className="list-panel"><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar terreno, uso o condición"/><b>{filtered.length}</b></div><div className="cards">{filtered.map(t=><button key={t.id} className={`terrain-card ${t.id===selected.id?'selected':''}`} onClick={()=>setSelectedId(t.id)}><div><span>{t.id}</span><em>{t.status}</em></div><strong>{t.name}</strong><p>{fmt(t.area)} m² · {t.use}</p><div className="score-row"><i>Eco {t.ecoPriority}</i><i>Des {t.feasibility}</i><i>Conf {t.confidence}</i></div></button>)}</div></aside><section className="map-section"><MapPanel terrains={data} selectedId={selected.id} onSelect={setSelectedId} onCreate={createTerrain} metric={metric}/></section><aside className="detail"><div className="detail-head"><span>{selected.id}</span><input className="title-input" value={selected.name} onChange={e=>patch('name',e.target.value)}/><p>{selected.status} · última actualización {selected.last}</p></div><div className="kpis"><K label="Superficie" value={`${fmt(selected.area)} m²`}/><K label="Eco prioridad" value={`${selected.ecoPriority}/100`}/><K label="Factibilidad" value={`${selected.feasibility}/100`}/><K label="Confianza" value={`${selected.confidence}/100`}/></div><section className="editor"><h3>Condición observada</h3><Slider label="Permeabilidad" value={selected.permeable} onChange={v=>patch('permeable',v)}/><Slider label="Superficie construida" value={selected.built} onChange={v=>patch('built',v)}/><Slider label="Accesibilidad" value={selected.access} onChange={v=>patch('access',v)}/><Slider label="Sensibilidad drenaje" value={selected.drainage} onChange={v=>patch('drainage',v)}/><Slider label="Vegetación" value={selected.vegetation} onChange={v=>patch('vegetation',v)}/><Slider label="Relleno / corte" value={selected.fill} onChange={v=>patch('fill',v)}/><Slider label="Cambio reciente" value={selected.change} onChange={v=>patch('change',v)}/><label className="numeric">Pendiente observada <input type="number" step=".1" value={selected.slope} onChange={e=>patch('slope',Number(e.target.value))}/><span>%</span></label></section><section className="decision"><h3>Interpretación operacional</h3>{actions(selected).map((a,i)=><div className={`action ${a.tone}`} key={i}><strong>{a.title}</strong><p>{a.why}</p><em>{a.task}</em></div>)}<button className="primary wide" onClick={()=>setTab('campo')}>Levantar este terreno</button></section></aside></main>}
 {tab==='campo'&&<FieldMission terrain={selected} onFinish={finishVisit}/>} 
 {tab==='acciones'&&<main className="actions-page"><div className="section-head"><div><span>COLA DE INSPECCIÓN</span><h2>Qué terreno requiere acción y por qué</h2></div></div>{urgent.map((t,idx)=><button className="priority-row" key={t.id} onClick={()=>{setSelectedId(t.id);setTab('campo')}}><b>{String(idx+1).padStart(2,'0')}</b><div><span>{t.id}</span><strong>{t.name}</strong><p>{actions(t)[0]?.title} · {actions(t)[0]?.why}</p></div><div className="priority-metrics"><i>Eco {t.ecoPriority}</i><i>Des {t.feasibility}</i><i>Δ {t.change}</i></div><em>Abrir misión →</em></button>)}</main>}
 {tab==='historial'&&<main className="history-page"><aside className="history-list">{data.map(t=><button className={t.id===selected.id?'active':''} key={t.id} onClick={()=>setSelectedId(t.id)}><span>{t.id}</span><strong>{t.name}</strong><em>{t.visits?.length||0} visitas</em></button>)}</aside><section className="history-detail"><div className="section-head"><div><span>EXPEDIENTE TEMPORAL</span><h2>{selected.name}</h2></div></div>{(selected.visits||[]).length?[...selected.visits].reverse().map((v,i)=><div className="visit-record" key={v.id}><div><span>{v.date} · {v.mode==='perimetro'?'Perímetro':'Inspección'}</span><strong>Visita #{selected.visits.length-i} · calidad {v.quality||'—'}/100</strong></div><div className="visit-metrics"><K label="Recorrido" value={`${v.distance.toFixed(0)} m`}/><K label="Cierre" value={v.closure!=null?`${v.closure.toFixed(0)} m`:'—'}/><K label="Precisión media" value={v.avgAcc!=null?`±${v.avgAcc.toFixed(0)} m`:'—'}/><K label="Rango vertical" value={v.altRange!=null?`${v.altRange.toFixed(1)} m`:'—'}/><K label="Puntos" value={v.points.length}/><K label="Área indicativa" value={v.walkedArea?`${fmt(v.walkedArea)} m²`:'—'}/></div>{v.evidence.length>0&&<div className="evidence-row">{v.evidence.map(e=><button key={e.id} onClick={()=>openEvidence(e.id)}>Abrir evidencia · {new Date(e.at).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</button>)}</div>}</div>):<div className="empty-history"><h3>Sin visitas cerradas</h3><p>Abre Campo, realiza un recorrido y cierra la visita. El resumen quedará aquí para comparar levantamientos posteriores.</p><button className="primary" onClick={()=>setTab('campo')}>Crear primera visita</button></div>}</section></main>}
 </div>
}
function K({label,value}){return <div className="k"><span>{label}</span><strong>{value}</strong></div>}
function Slider({label,value,onChange}){return <label className="slider"><div><span>{label}</span><b>{value}</b></div><input type="range" min="0" max="100" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
